
namespace Azar_Hotel
{
    partial class AddClientForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddClientForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.StreetLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.StreetBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CityLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.CityBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CountryLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.CountryBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NationalIDLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.NationalIDBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BirthdatePicker = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.BirthdateLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.GenderOption2Label = new Bunifu.UI.WinForms.BunifuLabel();
            this.GenderOption2 = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.GenderOption1Label = new Bunifu.UI.WinForms.BunifuLabel();
            this.GenderOption1 = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.GenderLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.PhoneNumberLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.PhoneNumberBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.EmailLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.EmailBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LastNameLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.FirstNameLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.LastNameBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.FirstNameBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AddBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Title = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(53)))), ((int)(((byte)(163)))));
            this.bunifuPanel1.BorderRadius = 10;
            this.bunifuPanel1.BorderThickness = 7;
            this.bunifuPanel1.Controls.Add(this.StreetLabel);
            this.bunifuPanel1.Controls.Add(this.StreetBox);
            this.bunifuPanel1.Controls.Add(this.CityLabel);
            this.bunifuPanel1.Controls.Add(this.CityBox);
            this.bunifuPanel1.Controls.Add(this.CountryLabel);
            this.bunifuPanel1.Controls.Add(this.CountryBox);
            this.bunifuPanel1.Controls.Add(this.NationalIDLabel);
            this.bunifuPanel1.Controls.Add(this.NationalIDBox);
            this.bunifuPanel1.Controls.Add(this.BirthdatePicker);
            this.bunifuPanel1.Controls.Add(this.BirthdateLabel);
            this.bunifuPanel1.Controls.Add(this.GenderOption2Label);
            this.bunifuPanel1.Controls.Add(this.GenderOption2);
            this.bunifuPanel1.Controls.Add(this.GenderOption1Label);
            this.bunifuPanel1.Controls.Add(this.GenderOption1);
            this.bunifuPanel1.Controls.Add(this.GenderLabel);
            this.bunifuPanel1.Controls.Add(this.PhoneNumberLabel);
            this.bunifuPanel1.Controls.Add(this.PhoneNumberBox);
            this.bunifuPanel1.Controls.Add(this.EmailLabel);
            this.bunifuPanel1.Controls.Add(this.EmailBox);
            this.bunifuPanel1.Controls.Add(this.LastNameLabel);
            this.bunifuPanel1.Controls.Add(this.FirstNameLabel);
            this.bunifuPanel1.Controls.Add(this.LastNameBox);
            this.bunifuPanel1.Controls.Add(this.FirstNameBox);
            this.bunifuPanel1.Controls.Add(this.AddBt);
            this.bunifuPanel1.Controls.Add(this.panel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(500, 500);
            this.bunifuPanel1.TabIndex = 2;
            // 
            // StreetLabel
            // 
            this.StreetLabel.AllowParentOverrides = false;
            this.StreetLabel.AutoEllipsis = false;
            this.StreetLabel.CursorType = null;
            this.StreetLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.StreetLabel.ForeColor = System.Drawing.Color.Indigo;
            this.StreetLabel.Location = new System.Drawing.Point(277, 253);
            this.StreetLabel.Name = "StreetLabel";
            this.StreetLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.StreetLabel.Size = new System.Drawing.Size(35, 15);
            this.StreetLabel.TabIndex = 35;
            this.StreetLabel.TabStop = false;
            this.StreetLabel.Text = "Street";
            this.StreetLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.StreetLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.StreetLabel.Visible = false;
            // 
            // StreetBox
            // 
            this.StreetBox.AcceptsReturn = false;
            this.StreetBox.AcceptsTab = false;
            this.StreetBox.AnimationSpeed = 200;
            this.StreetBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.StreetBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.StreetBox.BackColor = System.Drawing.Color.White;
            this.StreetBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("StreetBox.BackgroundImage")));
            this.StreetBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.StreetBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.StreetBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.StreetBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.StreetBox.BorderRadius = 7;
            this.StreetBox.BorderThickness = 3;
            this.StreetBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.StreetBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.StreetBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.StreetBox.DefaultText = "";
            this.StreetBox.FillColor = System.Drawing.Color.White;
            this.StreetBox.HideSelection = true;
            this.StreetBox.IconLeft = null;
            this.StreetBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.StreetBox.IconPadding = 15;
            this.StreetBox.IconRight = null;
            this.StreetBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.StreetBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.StreetBox.Lines = new string[0];
            this.StreetBox.Location = new System.Drawing.Point(275, 260);
            this.StreetBox.MaxLength = 20;
            this.StreetBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.StreetBox.Modified = false;
            this.StreetBox.Multiline = false;
            this.StreetBox.Name = "StreetBox";
            stateProperties1.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.StreetBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Gray;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.StreetBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties3.FillColor = System.Drawing.Color.White;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.StreetBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Indigo;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.StreetBox.OnIdleState = stateProperties4;
            this.StreetBox.Padding = new System.Windows.Forms.Padding(3);
            this.StreetBox.PasswordChar = '\0';
            this.StreetBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.StreetBox.PlaceholderText = "Street";
            this.StreetBox.ReadOnly = false;
            this.StreetBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.StreetBox.SelectedText = "";
            this.StreetBox.SelectionLength = 0;
            this.StreetBox.SelectionStart = 0;
            this.StreetBox.ShortcutsEnabled = true;
            this.StreetBox.Size = new System.Drawing.Size(200, 50);
            this.StreetBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.StreetBox.TabIndex = 7;
            this.StreetBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.StreetBox.TextMarginBottom = 0;
            this.StreetBox.TextMarginLeft = 10;
            this.StreetBox.TextMarginTop = 0;
            this.StreetBox.TextPlaceholder = "Street";
            this.StreetBox.UseSystemPasswordChar = false;
            this.StreetBox.WordWrap = true;
            this.StreetBox.TextChanged += new System.EventHandler(this.StreetBox_TextChanged);
            // 
            // CityLabel
            // 
            this.CityLabel.AllowParentOverrides = false;
            this.CityLabel.AutoEllipsis = false;
            this.CityLabel.CursorType = null;
            this.CityLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.CityLabel.ForeColor = System.Drawing.Color.Indigo;
            this.CityLabel.Location = new System.Drawing.Point(42, 253);
            this.CityLabel.Name = "CityLabel";
            this.CityLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.CityLabel.Size = new System.Drawing.Size(21, 15);
            this.CityLabel.TabIndex = 33;
            this.CityLabel.TabStop = false;
            this.CityLabel.Text = "City";
            this.CityLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.CityLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.CityLabel.Visible = false;
            // 
            // CityBox
            // 
            this.CityBox.AcceptsReturn = false;
            this.CityBox.AcceptsTab = false;
            this.CityBox.AnimationSpeed = 200;
            this.CityBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CityBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CityBox.BackColor = System.Drawing.Color.White;
            this.CityBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CityBox.BackgroundImage")));
            this.CityBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.CityBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.CityBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.CityBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.CityBox.BorderRadius = 7;
            this.CityBox.BorderThickness = 3;
            this.CityBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CityBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CityBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CityBox.DefaultText = "";
            this.CityBox.FillColor = System.Drawing.Color.White;
            this.CityBox.HideSelection = true;
            this.CityBox.IconLeft = null;
            this.CityBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CityBox.IconPadding = 15;
            this.CityBox.IconRight = null;
            this.CityBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CityBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.CityBox.Lines = new string[0];
            this.CityBox.Location = new System.Drawing.Point(40, 260);
            this.CityBox.MaxLength = 20;
            this.CityBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.CityBox.Modified = false;
            this.CityBox.Multiline = false;
            this.CityBox.Name = "CityBox";
            stateProperties5.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties5.FillColor = System.Drawing.Color.White;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CityBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Gray;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CityBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties7.FillColor = System.Drawing.Color.White;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CityBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Indigo;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CityBox.OnIdleState = stateProperties8;
            this.CityBox.Padding = new System.Windows.Forms.Padding(3);
            this.CityBox.PasswordChar = '\0';
            this.CityBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.CityBox.PlaceholderText = "City";
            this.CityBox.ReadOnly = false;
            this.CityBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CityBox.SelectedText = "";
            this.CityBox.SelectionLength = 0;
            this.CityBox.SelectionStart = 0;
            this.CityBox.ShortcutsEnabled = true;
            this.CityBox.Size = new System.Drawing.Size(200, 50);
            this.CityBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.CityBox.TabIndex = 6;
            this.CityBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CityBox.TextMarginBottom = 0;
            this.CityBox.TextMarginLeft = 10;
            this.CityBox.TextMarginTop = 0;
            this.CityBox.TextPlaceholder = "City";
            this.CityBox.UseSystemPasswordChar = false;
            this.CityBox.WordWrap = true;
            this.CityBox.TextChanged += new System.EventHandler(this.CityBox_TextChanged);
            // 
            // CountryLabel
            // 
            this.CountryLabel.AllowParentOverrides = false;
            this.CountryLabel.AutoEllipsis = false;
            this.CountryLabel.CursorType = null;
            this.CountryLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.CountryLabel.ForeColor = System.Drawing.Color.Indigo;
            this.CountryLabel.Location = new System.Drawing.Point(277, 188);
            this.CountryLabel.Name = "CountryLabel";
            this.CountryLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.CountryLabel.Size = new System.Drawing.Size(44, 15);
            this.CountryLabel.TabIndex = 31;
            this.CountryLabel.TabStop = false;
            this.CountryLabel.Text = "Country";
            this.CountryLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.CountryLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.CountryLabel.Visible = false;
            // 
            // CountryBox
            // 
            this.CountryBox.AcceptsReturn = false;
            this.CountryBox.AcceptsTab = false;
            this.CountryBox.AnimationSpeed = 200;
            this.CountryBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CountryBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CountryBox.BackColor = System.Drawing.Color.White;
            this.CountryBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CountryBox.BackgroundImage")));
            this.CountryBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.CountryBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.CountryBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.CountryBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.CountryBox.BorderRadius = 7;
            this.CountryBox.BorderThickness = 3;
            this.CountryBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CountryBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CountryBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CountryBox.DefaultText = "";
            this.CountryBox.FillColor = System.Drawing.Color.White;
            this.CountryBox.HideSelection = true;
            this.CountryBox.IconLeft = null;
            this.CountryBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CountryBox.IconPadding = 15;
            this.CountryBox.IconRight = null;
            this.CountryBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CountryBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.CountryBox.Lines = new string[0];
            this.CountryBox.Location = new System.Drawing.Point(275, 195);
            this.CountryBox.MaxLength = 20;
            this.CountryBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.CountryBox.Modified = false;
            this.CountryBox.Multiline = false;
            this.CountryBox.Name = "CountryBox";
            stateProperties9.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties9.FillColor = System.Drawing.Color.White;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CountryBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Gray;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CountryBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties11.FillColor = System.Drawing.Color.White;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CountryBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Indigo;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CountryBox.OnIdleState = stateProperties12;
            this.CountryBox.Padding = new System.Windows.Forms.Padding(3);
            this.CountryBox.PasswordChar = '\0';
            this.CountryBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.CountryBox.PlaceholderText = "Country";
            this.CountryBox.ReadOnly = false;
            this.CountryBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CountryBox.SelectedText = "";
            this.CountryBox.SelectionLength = 0;
            this.CountryBox.SelectionStart = 0;
            this.CountryBox.ShortcutsEnabled = true;
            this.CountryBox.Size = new System.Drawing.Size(200, 50);
            this.CountryBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.CountryBox.TabIndex = 5;
            this.CountryBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CountryBox.TextMarginBottom = 0;
            this.CountryBox.TextMarginLeft = 10;
            this.CountryBox.TextMarginTop = 0;
            this.CountryBox.TextPlaceholder = "Country";
            this.CountryBox.UseSystemPasswordChar = false;
            this.CountryBox.WordWrap = true;
            this.CountryBox.TextChanged += new System.EventHandler(this.CountryBox_TextChanged);
            // 
            // NationalIDLabel
            // 
            this.NationalIDLabel.AllowParentOverrides = false;
            this.NationalIDLabel.AutoEllipsis = false;
            this.NationalIDLabel.CursorType = null;
            this.NationalIDLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.NationalIDLabel.ForeColor = System.Drawing.Color.Indigo;
            this.NationalIDLabel.Location = new System.Drawing.Point(42, 188);
            this.NationalIDLabel.Name = "NationalIDLabel";
            this.NationalIDLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.NationalIDLabel.Size = new System.Drawing.Size(60, 15);
            this.NationalIDLabel.TabIndex = 29;
            this.NationalIDLabel.TabStop = false;
            this.NationalIDLabel.Text = "National ID";
            this.NationalIDLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.NationalIDLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.NationalIDLabel.Visible = false;
            // 
            // NationalIDBox
            // 
            this.NationalIDBox.AcceptsReturn = false;
            this.NationalIDBox.AcceptsTab = false;
            this.NationalIDBox.AnimationSpeed = 200;
            this.NationalIDBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NationalIDBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NationalIDBox.BackColor = System.Drawing.Color.White;
            this.NationalIDBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NationalIDBox.BackgroundImage")));
            this.NationalIDBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.NationalIDBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.NationalIDBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.NationalIDBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.NationalIDBox.BorderRadius = 7;
            this.NationalIDBox.BorderThickness = 3;
            this.NationalIDBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NationalIDBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NationalIDBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NationalIDBox.DefaultText = "";
            this.NationalIDBox.FillColor = System.Drawing.Color.White;
            this.NationalIDBox.HideSelection = true;
            this.NationalIDBox.IconLeft = null;
            this.NationalIDBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NationalIDBox.IconPadding = 15;
            this.NationalIDBox.IconRight = null;
            this.NationalIDBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NationalIDBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.NationalIDBox.Lines = new string[0];
            this.NationalIDBox.Location = new System.Drawing.Point(40, 195);
            this.NationalIDBox.MaxLength = 20;
            this.NationalIDBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.NationalIDBox.Modified = false;
            this.NationalIDBox.Multiline = false;
            this.NationalIDBox.Name = "NationalIDBox";
            stateProperties13.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties13.FillColor = System.Drawing.Color.White;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NationalIDBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Gray;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NationalIDBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties15.FillColor = System.Drawing.Color.White;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NationalIDBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Indigo;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NationalIDBox.OnIdleState = stateProperties16;
            this.NationalIDBox.Padding = new System.Windows.Forms.Padding(3);
            this.NationalIDBox.PasswordChar = '\0';
            this.NationalIDBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.NationalIDBox.PlaceholderText = "National ID";
            this.NationalIDBox.ReadOnly = false;
            this.NationalIDBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NationalIDBox.SelectedText = "";
            this.NationalIDBox.SelectionLength = 0;
            this.NationalIDBox.SelectionStart = 0;
            this.NationalIDBox.ShortcutsEnabled = true;
            this.NationalIDBox.Size = new System.Drawing.Size(200, 50);
            this.NationalIDBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.NationalIDBox.TabIndex = 4;
            this.NationalIDBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NationalIDBox.TextMarginBottom = 0;
            this.NationalIDBox.TextMarginLeft = 10;
            this.NationalIDBox.TextMarginTop = 0;
            this.NationalIDBox.TextPlaceholder = "National ID";
            this.NationalIDBox.UseSystemPasswordChar = false;
            this.NationalIDBox.WordWrap = true;
            this.NationalIDBox.TextChanged += new System.EventHandler(this.NationalIDBox_TextChanged);
            // 
            // BirthdatePicker
            // 
            this.BirthdatePicker.BackColor = System.Drawing.Color.Transparent;
            this.BirthdatePicker.BorderRadius = 1;
            this.BirthdatePicker.Color = System.Drawing.Color.Silver;
            this.BirthdatePicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.BirthdatePicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.BirthdatePicker.DisabledColor = System.Drawing.Color.Gray;
            this.BirthdatePicker.DisplayWeekNumbers = false;
            this.BirthdatePicker.DPHeight = 0;
            this.BirthdatePicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.BirthdatePicker.FillDatePicker = false;
            this.BirthdatePicker.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BirthdatePicker.ForeColor = System.Drawing.Color.Black;
            this.BirthdatePicker.Icon = ((System.Drawing.Image)(resources.GetObject("BirthdatePicker.Icon")));
            this.BirthdatePicker.IconColor = System.Drawing.Color.Gray;
            this.BirthdatePicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.BirthdatePicker.LeftTextMargin = 5;
            this.BirthdatePicker.Location = new System.Drawing.Point(203, 373);
            this.BirthdatePicker.MaxDate = new System.DateTime(2022, 12, 19, 7, 41, 7, 346);
            this.BirthdatePicker.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.BirthdatePicker.MinimumSize = new System.Drawing.Size(4, 32);
            this.BirthdatePicker.Name = "BirthdatePicker";
            this.BirthdatePicker.Size = new System.Drawing.Size(194, 32);
            this.BirthdatePicker.TabIndex = 10;
            this.BirthdatePicker.TabStop = false;
            this.BirthdatePicker.Value = new System.DateTime(2000, 1, 1, 0, 0, 0, 0);
            // 
            // BirthdateLabel
            // 
            this.BirthdateLabel.AllowParentOverrides = false;
            this.BirthdateLabel.AutoEllipsis = false;
            this.BirthdateLabel.CursorType = null;
            this.BirthdateLabel.Font = new System.Drawing.Font("Calibri", 15.75F, System.Drawing.FontStyle.Bold);
            this.BirthdateLabel.ForeColor = System.Drawing.Color.Indigo;
            this.BirthdateLabel.Location = new System.Drawing.Point(103, 375);
            this.BirthdateLabel.Name = "BirthdateLabel";
            this.BirthdateLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.BirthdateLabel.Size = new System.Drawing.Size(92, 26);
            this.BirthdateLabel.TabIndex = 27;
            this.BirthdateLabel.TabStop = false;
            this.BirthdateLabel.Text = "Birthdate :";
            this.BirthdateLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.BirthdateLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // GenderOption2Label
            // 
            this.GenderOption2Label.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.GenderOption2Label.AllowParentOverrides = false;
            this.GenderOption2Label.AutoEllipsis = false;
            this.GenderOption2Label.CursorType = null;
            this.GenderOption2Label.Font = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold);
            this.GenderOption2Label.ForeColor = System.Drawing.Color.Indigo;
            this.GenderOption2Label.Location = new System.Drawing.Point(320, 333);
            this.GenderOption2Label.Name = "GenderOption2Label";
            this.GenderOption2Label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.GenderOption2Label.Size = new System.Drawing.Size(58, 23);
            this.GenderOption2Label.TabIndex = 26;
            this.GenderOption2Label.TabStop = false;
            this.GenderOption2Label.Text = "Female";
            this.GenderOption2Label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.GenderOption2Label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // GenderOption2
            // 
            this.GenderOption2.AllowBindingControlLocation = false;
            this.GenderOption2.BackColor = System.Drawing.Color.Transparent;
            this.GenderOption2.BindingControl = this.GenderOption2Label;
            this.GenderOption2.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.GenderOption2.BorderThickness = 1;
            this.GenderOption2.Checked = false;
            this.GenderOption2.Location = new System.Drawing.Point(290, 332);
            this.GenderOption2.Name = "GenderOption2";
            this.GenderOption2.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.GenderOption2.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.GenderOption2.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.GenderOption2.RadioColor = System.Drawing.Color.DodgerBlue;
            this.GenderOption2.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.GenderOption2.Size = new System.Drawing.Size(24, 24);
            this.GenderOption2.TabIndex = 9;
            this.GenderOption2.Text = null;
            // 
            // GenderOption1Label
            // 
            this.GenderOption1Label.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.GenderOption1Label.AllowParentOverrides = false;
            this.GenderOption1Label.AutoEllipsis = false;
            this.GenderOption1Label.CursorType = null;
            this.GenderOption1Label.Font = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold);
            this.GenderOption1Label.ForeColor = System.Drawing.Color.Indigo;
            this.GenderOption1Label.Location = new System.Drawing.Point(233, 333);
            this.GenderOption1Label.Name = "GenderOption1Label";
            this.GenderOption1Label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.GenderOption1Label.Size = new System.Drawing.Size(41, 23);
            this.GenderOption1Label.TabIndex = 24;
            this.GenderOption1Label.TabStop = false;
            this.GenderOption1Label.Text = "Male";
            this.GenderOption1Label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.GenderOption1Label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // GenderOption1
            // 
            this.GenderOption1.AllowBindingControlLocation = false;
            this.GenderOption1.BackColor = System.Drawing.Color.Transparent;
            this.GenderOption1.BindingControl = this.GenderOption1Label;
            this.GenderOption1.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.GenderOption1.BorderThickness = 1;
            this.GenderOption1.Checked = true;
            this.GenderOption1.Location = new System.Drawing.Point(203, 333);
            this.GenderOption1.Name = "GenderOption1";
            this.GenderOption1.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.GenderOption1.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.GenderOption1.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.GenderOption1.RadioColor = System.Drawing.Color.DodgerBlue;
            this.GenderOption1.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.GenderOption1.Size = new System.Drawing.Size(24, 24);
            this.GenderOption1.TabIndex = 8;
            this.GenderOption1.Text = null;
            // 
            // GenderLabel
            // 
            this.GenderLabel.AllowParentOverrides = false;
            this.GenderLabel.AutoEllipsis = false;
            this.GenderLabel.CursorType = null;
            this.GenderLabel.Font = new System.Drawing.Font("Calibri", 15.75F, System.Drawing.FontStyle.Bold);
            this.GenderLabel.ForeColor = System.Drawing.Color.Indigo;
            this.GenderLabel.Location = new System.Drawing.Point(122, 330);
            this.GenderLabel.Name = "GenderLabel";
            this.GenderLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.GenderLabel.Size = new System.Drawing.Size(75, 26);
            this.GenderLabel.TabIndex = 22;
            this.GenderLabel.Text = "Gender :";
            this.GenderLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.GenderLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PhoneNumberLabel
            // 
            this.PhoneNumberLabel.AllowParentOverrides = false;
            this.PhoneNumberLabel.AutoEllipsis = false;
            this.PhoneNumberLabel.CursorType = null;
            this.PhoneNumberLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.PhoneNumberLabel.ForeColor = System.Drawing.Color.Indigo;
            this.PhoneNumberLabel.Location = new System.Drawing.Point(277, 123);
            this.PhoneNumberLabel.Name = "PhoneNumberLabel";
            this.PhoneNumberLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.PhoneNumberLabel.Size = new System.Drawing.Size(84, 15);
            this.PhoneNumberLabel.TabIndex = 20;
            this.PhoneNumberLabel.TabStop = false;
            this.PhoneNumberLabel.Text = "Phone Number";
            this.PhoneNumberLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.PhoneNumberLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.PhoneNumberLabel.Visible = false;
            // 
            // PhoneNumberBox
            // 
            this.PhoneNumberBox.AcceptsReturn = false;
            this.PhoneNumberBox.AcceptsTab = false;
            this.PhoneNumberBox.AnimationSpeed = 200;
            this.PhoneNumberBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PhoneNumberBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PhoneNumberBox.BackColor = System.Drawing.Color.White;
            this.PhoneNumberBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PhoneNumberBox.BackgroundImage")));
            this.PhoneNumberBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.PhoneNumberBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.PhoneNumberBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.PhoneNumberBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.PhoneNumberBox.BorderRadius = 7;
            this.PhoneNumberBox.BorderThickness = 3;
            this.PhoneNumberBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PhoneNumberBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneNumberBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PhoneNumberBox.DefaultText = "";
            this.PhoneNumberBox.FillColor = System.Drawing.Color.White;
            this.PhoneNumberBox.HideSelection = true;
            this.PhoneNumberBox.IconLeft = null;
            this.PhoneNumberBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneNumberBox.IconPadding = 15;
            this.PhoneNumberBox.IconRight = null;
            this.PhoneNumberBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneNumberBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.PhoneNumberBox.Lines = new string[0];
            this.PhoneNumberBox.Location = new System.Drawing.Point(275, 130);
            this.PhoneNumberBox.MaxLength = 20;
            this.PhoneNumberBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PhoneNumberBox.Modified = false;
            this.PhoneNumberBox.Multiline = false;
            this.PhoneNumberBox.Name = "PhoneNumberBox";
            stateProperties17.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties17.FillColor = System.Drawing.Color.White;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneNumberBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Gray;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PhoneNumberBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties19.FillColor = System.Drawing.Color.White;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneNumberBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Indigo;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneNumberBox.OnIdleState = stateProperties20;
            this.PhoneNumberBox.Padding = new System.Windows.Forms.Padding(3);
            this.PhoneNumberBox.PasswordChar = '\0';
            this.PhoneNumberBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.PhoneNumberBox.PlaceholderText = "Phone Number";
            this.PhoneNumberBox.ReadOnly = false;
            this.PhoneNumberBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PhoneNumberBox.SelectedText = "";
            this.PhoneNumberBox.SelectionLength = 0;
            this.PhoneNumberBox.SelectionStart = 0;
            this.PhoneNumberBox.ShortcutsEnabled = true;
            this.PhoneNumberBox.Size = new System.Drawing.Size(200, 50);
            this.PhoneNumberBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.PhoneNumberBox.TabIndex = 3;
            this.PhoneNumberBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PhoneNumberBox.TextMarginBottom = 0;
            this.PhoneNumberBox.TextMarginLeft = 10;
            this.PhoneNumberBox.TextMarginTop = 0;
            this.PhoneNumberBox.TextPlaceholder = "Phone Number";
            this.PhoneNumberBox.UseSystemPasswordChar = false;
            this.PhoneNumberBox.WordWrap = true;
            this.PhoneNumberBox.TextChanged += new System.EventHandler(this.PhoneNumberBox_TextChanged);
            // 
            // EmailLabel
            // 
            this.EmailLabel.AllowParentOverrides = false;
            this.EmailLabel.AutoEllipsis = false;
            this.EmailLabel.CursorType = null;
            this.EmailLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.EmailLabel.ForeColor = System.Drawing.Color.Indigo;
            this.EmailLabel.Location = new System.Drawing.Point(42, 123);
            this.EmailLabel.Name = "EmailLabel";
            this.EmailLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.EmailLabel.Size = new System.Drawing.Size(29, 15);
            this.EmailLabel.TabIndex = 18;
            this.EmailLabel.TabStop = false;
            this.EmailLabel.Text = "Email";
            this.EmailLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.EmailLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.EmailLabel.Visible = false;
            // 
            // EmailBox
            // 
            this.EmailBox.AcceptsReturn = false;
            this.EmailBox.AcceptsTab = false;
            this.EmailBox.AnimationSpeed = 200;
            this.EmailBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmailBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmailBox.BackColor = System.Drawing.Color.White;
            this.EmailBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmailBox.BackgroundImage")));
            this.EmailBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.EmailBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.EmailBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.EmailBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.EmailBox.BorderRadius = 7;
            this.EmailBox.BorderThickness = 3;
            this.EmailBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmailBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.EmailBox.DefaultText = "";
            this.EmailBox.FillColor = System.Drawing.Color.White;
            this.EmailBox.HideSelection = true;
            this.EmailBox.IconLeft = null;
            this.EmailBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailBox.IconPadding = 15;
            this.EmailBox.IconRight = null;
            this.EmailBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.EmailBox.Lines = new string[0];
            this.EmailBox.Location = new System.Drawing.Point(40, 130);
            this.EmailBox.MaxLength = 20;
            this.EmailBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.EmailBox.Modified = false;
            this.EmailBox.Multiline = false;
            this.EmailBox.Name = "EmailBox";
            stateProperties21.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties21.FillColor = System.Drawing.Color.White;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailBox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Gray;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmailBox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties23.FillColor = System.Drawing.Color.White;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailBox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Indigo;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailBox.OnIdleState = stateProperties24;
            this.EmailBox.Padding = new System.Windows.Forms.Padding(3);
            this.EmailBox.PasswordChar = '\0';
            this.EmailBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.EmailBox.PlaceholderText = "Email";
            this.EmailBox.ReadOnly = false;
            this.EmailBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmailBox.SelectedText = "";
            this.EmailBox.SelectionLength = 0;
            this.EmailBox.SelectionStart = 0;
            this.EmailBox.ShortcutsEnabled = true;
            this.EmailBox.Size = new System.Drawing.Size(200, 50);
            this.EmailBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.EmailBox.TabIndex = 2;
            this.EmailBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmailBox.TextMarginBottom = 0;
            this.EmailBox.TextMarginLeft = 10;
            this.EmailBox.TextMarginTop = 0;
            this.EmailBox.TextPlaceholder = "Email";
            this.EmailBox.UseSystemPasswordChar = false;
            this.EmailBox.WordWrap = true;
            this.EmailBox.TextChanged += new System.EventHandler(this.EmailBox_TextChanged);
            // 
            // LastNameLabel
            // 
            this.LastNameLabel.AllowParentOverrides = false;
            this.LastNameLabel.AutoEllipsis = false;
            this.LastNameLabel.CursorType = null;
            this.LastNameLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.LastNameLabel.ForeColor = System.Drawing.Color.Indigo;
            this.LastNameLabel.Location = new System.Drawing.Point(277, 58);
            this.LastNameLabel.Name = "LastNameLabel";
            this.LastNameLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LastNameLabel.Size = new System.Drawing.Size(58, 15);
            this.LastNameLabel.TabIndex = 14;
            this.LastNameLabel.TabStop = false;
            this.LastNameLabel.Text = "Last Name";
            this.LastNameLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LastNameLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LastNameLabel.Visible = false;
            // 
            // FirstNameLabel
            // 
            this.FirstNameLabel.AllowParentOverrides = false;
            this.FirstNameLabel.AutoEllipsis = false;
            this.FirstNameLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.FirstNameLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.FirstNameLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.FirstNameLabel.ForeColor = System.Drawing.Color.Indigo;
            this.FirstNameLabel.Location = new System.Drawing.Point(42, 58);
            this.FirstNameLabel.Name = "FirstNameLabel";
            this.FirstNameLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.FirstNameLabel.Size = new System.Drawing.Size(60, 15);
            this.FirstNameLabel.TabIndex = 13;
            this.FirstNameLabel.TabStop = false;
            this.FirstNameLabel.Text = "First Name";
            this.FirstNameLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.FirstNameLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.FirstNameLabel.Visible = false;
            // 
            // LastNameBox
            // 
            this.LastNameBox.AcceptsReturn = false;
            this.LastNameBox.AcceptsTab = false;
            this.LastNameBox.AnimationSpeed = 200;
            this.LastNameBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.LastNameBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.LastNameBox.BackColor = System.Drawing.Color.White;
            this.LastNameBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LastNameBox.BackgroundImage")));
            this.LastNameBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.LastNameBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.LastNameBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.LastNameBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.LastNameBox.BorderRadius = 7;
            this.LastNameBox.BorderThickness = 3;
            this.LastNameBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.LastNameBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.LastNameBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LastNameBox.DefaultText = "";
            this.LastNameBox.FillColor = System.Drawing.Color.White;
            this.LastNameBox.HideSelection = true;
            this.LastNameBox.IconLeft = null;
            this.LastNameBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.LastNameBox.IconPadding = 15;
            this.LastNameBox.IconRight = null;
            this.LastNameBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.LastNameBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.LastNameBox.Lines = new string[0];
            this.LastNameBox.Location = new System.Drawing.Point(275, 65);
            this.LastNameBox.MaxLength = 20;
            this.LastNameBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.LastNameBox.Modified = false;
            this.LastNameBox.Multiline = false;
            this.LastNameBox.Name = "LastNameBox";
            stateProperties25.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties25.FillColor = System.Drawing.Color.White;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LastNameBox.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Gray;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.LastNameBox.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties27.FillColor = System.Drawing.Color.White;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LastNameBox.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Indigo;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LastNameBox.OnIdleState = stateProperties28;
            this.LastNameBox.Padding = new System.Windows.Forms.Padding(3);
            this.LastNameBox.PasswordChar = '\0';
            this.LastNameBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.LastNameBox.PlaceholderText = "Last Name";
            this.LastNameBox.ReadOnly = false;
            this.LastNameBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.LastNameBox.SelectedText = "";
            this.LastNameBox.SelectionLength = 0;
            this.LastNameBox.SelectionStart = 0;
            this.LastNameBox.ShortcutsEnabled = true;
            this.LastNameBox.Size = new System.Drawing.Size(200, 50);
            this.LastNameBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.LastNameBox.TabIndex = 1;
            this.LastNameBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.LastNameBox.TextMarginBottom = 0;
            this.LastNameBox.TextMarginLeft = 10;
            this.LastNameBox.TextMarginTop = 0;
            this.LastNameBox.TextPlaceholder = "Last Name";
            this.LastNameBox.UseSystemPasswordChar = false;
            this.LastNameBox.WordWrap = true;
            this.LastNameBox.TextChanged += new System.EventHandler(this.LastNameBox_TextChanged);
            // 
            // FirstNameBox
            // 
            this.FirstNameBox.AcceptsReturn = false;
            this.FirstNameBox.AcceptsTab = false;
            this.FirstNameBox.AnimationSpeed = 200;
            this.FirstNameBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.FirstNameBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.FirstNameBox.BackColor = System.Drawing.Color.White;
            this.FirstNameBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("FirstNameBox.BackgroundImage")));
            this.FirstNameBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.FirstNameBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.FirstNameBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.FirstNameBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.FirstNameBox.BorderRadius = 7;
            this.FirstNameBox.BorderThickness = 3;
            this.FirstNameBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.FirstNameBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FirstNameBox.DefaultText = "";
            this.FirstNameBox.FillColor = System.Drawing.Color.White;
            this.FirstNameBox.HideSelection = true;
            this.FirstNameBox.IconLeft = null;
            this.FirstNameBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameBox.IconPadding = 15;
            this.FirstNameBox.IconRight = null;
            this.FirstNameBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.FirstNameBox.Lines = new string[0];
            this.FirstNameBox.Location = new System.Drawing.Point(40, 65);
            this.FirstNameBox.MaxLength = 20;
            this.FirstNameBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.FirstNameBox.Modified = false;
            this.FirstNameBox.Multiline = false;
            this.FirstNameBox.Name = "FirstNameBox";
            stateProperties29.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties29.FillColor = System.Drawing.Color.White;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameBox.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Gray;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.FirstNameBox.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties31.FillColor = System.Drawing.Color.White;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameBox.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Indigo;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameBox.OnIdleState = stateProperties32;
            this.FirstNameBox.Padding = new System.Windows.Forms.Padding(3);
            this.FirstNameBox.PasswordChar = '\0';
            this.FirstNameBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.FirstNameBox.PlaceholderText = "First Name";
            this.FirstNameBox.ReadOnly = false;
            this.FirstNameBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.FirstNameBox.SelectedText = "";
            this.FirstNameBox.SelectionLength = 0;
            this.FirstNameBox.SelectionStart = 0;
            this.FirstNameBox.ShortcutsEnabled = true;
            this.FirstNameBox.Size = new System.Drawing.Size(200, 50);
            this.FirstNameBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.FirstNameBox.TabIndex = 0;
            this.FirstNameBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.FirstNameBox.TextMarginBottom = 0;
            this.FirstNameBox.TextMarginLeft = 10;
            this.FirstNameBox.TextMarginTop = 0;
            this.FirstNameBox.TextPlaceholder = "First Name";
            this.FirstNameBox.UseSystemPasswordChar = false;
            this.FirstNameBox.WordWrap = true;
            this.FirstNameBox.TextChanged += new System.EventHandler(this.FirstNameBox_TextChanged);
            // 
            // AddBt
            // 
            this.AddBt.AllowAnimations = true;
            this.AddBt.AllowMouseEffects = true;
            this.AddBt.AllowToggling = false;
            this.AddBt.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.AddBt.AnimationSpeed = 200;
            this.AddBt.AutoGenerateColors = false;
            this.AddBt.AutoRoundBorders = false;
            this.AddBt.AutoSizeLeftIcon = true;
            this.AddBt.AutoSizeRightIcon = true;
            this.AddBt.BackColor = System.Drawing.Color.Transparent;
            this.AddBt.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddBt.BackgroundImage")));
            this.AddBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.ButtonText = "Add";
            this.AddBt.ButtonTextMarginLeft = 0;
            this.AddBt.ColorContrastOnClick = 45;
            this.AddBt.ColorContrastOnHover = 45;
            this.AddBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AddBt.CustomizableEdges = borderEdges1;
            this.AddBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddBt.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AddBt.ForeColor = System.Drawing.Color.White;
            this.AddBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddBt.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.AddBt.IconMarginLeft = 11;
            this.AddBt.IconPadding = 10;
            this.AddBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddBt.IconRightPadding = new System.Windows.Forms.Padding(15);
            this.AddBt.IconSize = 25;
            this.AddBt.IdleBorderColor = System.Drawing.Color.Transparent;
            this.AddBt.IdleBorderRadius = 7;
            this.AddBt.IdleBorderThickness = 1;
            this.AddBt.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.IdleIconLeftImage = null;
            this.AddBt.IdleIconRightImage = null;
            this.AddBt.IndicateFocus = false;
            this.AddBt.Location = new System.Drawing.Point(42, 426);
            this.AddBt.Name = "AddBt";
            this.AddBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddBt.OnDisabledState.BorderRadius = 7;
            this.AddBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnDisabledState.BorderThickness = 1;
            this.AddBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddBt.OnDisabledState.IconLeftImage = null;
            this.AddBt.OnDisabledState.IconRightImage = null;
            this.AddBt.onHoverState.BorderColor = System.Drawing.Color.BlueViolet;
            this.AddBt.onHoverState.BorderRadius = 7;
            this.AddBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.onHoverState.BorderThickness = 1;
            this.AddBt.onHoverState.FillColor = System.Drawing.Color.BlueViolet;
            this.AddBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddBt.onHoverState.IconLeftImage = null;
            this.AddBt.onHoverState.IconRightImage = null;
            this.AddBt.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.AddBt.OnIdleState.BorderRadius = 7;
            this.AddBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnIdleState.BorderThickness = 1;
            this.AddBt.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AddBt.OnIdleState.IconLeftImage = null;
            this.AddBt.OnIdleState.IconRightImage = null;
            this.AddBt.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.AddBt.OnPressedState.BorderRadius = 7;
            this.AddBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnPressedState.BorderThickness = 1;
            this.AddBt.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.AddBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddBt.OnPressedState.IconLeftImage = null;
            this.AddBt.OnPressedState.IconRightImage = null;
            this.AddBt.Size = new System.Drawing.Size(433, 50);
            this.AddBt.TabIndex = 10;
            this.AddBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddBt.TextMarginLeft = 0;
            this.AddBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddBt.UseDefaultRadiusAndThickness = true;
            this.AddBt.Click += new System.EventHandler(this.AddBt_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(53)))), ((int)(((byte)(163)))));
            this.panel1.Controls.Add(this.btClose);
            this.panel1.Controls.Add(this.Title);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(500, 40);
            this.panel1.TabIndex = 11;
            // 
            // btClose
            // 
            this.btClose.AllowAnimations = true;
            this.btClose.AllowMouseEffects = true;
            this.btClose.AllowToggling = false;
            this.btClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btClose.AnimationSpeed = 200;
            this.btClose.AutoGenerateColors = false;
            this.btClose.AutoRoundBorders = false;
            this.btClose.AutoSizeLeftIcon = true;
            this.btClose.AutoSizeRightIcon = true;
            this.btClose.BackColor = System.Drawing.Color.Transparent;
            this.btClose.BackColor1 = System.Drawing.Color.Transparent;
            this.btClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btClose.BackgroundImage")));
            this.btClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.ButtonText = "";
            this.btClose.ButtonTextMarginLeft = 0;
            this.btClose.ColorContrastOnClick = 45;
            this.btClose.ColorContrastOnHover = 45;
            this.btClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btClose.CustomizableEdges = borderEdges2;
            this.btClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btClose.ForeColor = System.Drawing.Color.Transparent;
            this.btClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btClose.IconLeftPadding = new System.Windows.Forms.Padding(4);
            this.btClose.IconMarginLeft = 11;
            this.btClose.IconPadding = 5;
            this.btClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btClose.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btClose.IconSize = 25;
            this.btClose.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btClose.IdleBorderRadius = 3;
            this.btClose.IdleBorderThickness = 1;
            this.btClose.IdleFillColor = System.Drawing.Color.Transparent;
            this.btClose.IdleIconLeftImage = global::Azar_Hotel.Properties.Resources.close;
            this.btClose.IdleIconRightImage = null;
            this.btClose.IndicateFocus = false;
            this.btClose.Location = new System.Drawing.Point(468, 6);
            this.btClose.Name = "btClose";
            this.btClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btClose.OnDisabledState.BorderRadius = 3;
            this.btClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnDisabledState.BorderThickness = 1;
            this.btClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btClose.OnDisabledState.IconLeftImage = null;
            this.btClose.OnDisabledState.IconRightImage = null;
            this.btClose.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.btClose.onHoverState.BorderRadius = 3;
            this.btClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.onHoverState.BorderThickness = 1;
            this.btClose.onHoverState.FillColor = System.Drawing.Color.Red;
            this.btClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btClose.onHoverState.IconLeftImage = null;
            this.btClose.onHoverState.IconRightImage = null;
            this.btClose.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.BorderRadius = 3;
            this.btClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnIdleState.BorderThickness = 1;
            this.btClose.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.IconLeftImage = global::Azar_Hotel.Properties.Resources.close;
            this.btClose.OnIdleState.IconRightImage = null;
            this.btClose.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.btClose.OnPressedState.BorderRadius = 3;
            this.btClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnPressedState.BorderThickness = 1;
            this.btClose.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.btClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btClose.OnPressedState.IconLeftImage = null;
            this.btClose.OnPressedState.IconRightImage = null;
            this.btClose.Size = new System.Drawing.Size(25, 25);
            this.btClose.TabIndex = 11;
            this.btClose.TabStop = false;
            this.btClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btClose.TextMarginLeft = 0;
            this.btClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btClose.UseDefaultRadiusAndThickness = true;
            this.btClose.Click += new System.EventHandler(this.CloseBt_Click);
            // 
            // Title
            // 
            this.Title.AllowParentOverrides = false;
            this.Title.AutoEllipsis = false;
            this.Title.AutoSize = false;
            this.Title.Cursor = System.Windows.Forms.Cursors.Default;
            this.Title.CursorType = System.Windows.Forms.Cursors.Default;
            this.Title.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Title.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold);
            this.Title.ForeColor = System.Drawing.Color.White;
            this.Title.Location = new System.Drawing.Point(0, 0);
            this.Title.Name = "Title";
            this.Title.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Title.Size = new System.Drawing.Size(500, 40);
            this.Title.TabIndex = 0;
            this.Title.TabStop = false;
            this.Title.Text = "Add";
            this.Title.TextAlignment = System.Drawing.ContentAlignment.BottomCenter;
            this.Title.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.Title.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form_MouseDown);
            // 
            // AddClientForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(500, 500);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AddClientForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "AddForm";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AddBt;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btClose;
        private Bunifu.UI.WinForms.BunifuLabel Title;
        private Bunifu.UI.WinForms.BunifuLabel LastNameLabel;
        private Bunifu.UI.WinForms.BunifuLabel FirstNameLabel;
        private Bunifu.UI.WinForms.BunifuLabel StreetLabel;
        private Bunifu.UI.WinForms.BunifuTextBox StreetBox;
        private Bunifu.UI.WinForms.BunifuLabel CityLabel;
        private Bunifu.UI.WinForms.BunifuTextBox CityBox;
        private Bunifu.UI.WinForms.BunifuLabel CountryLabel;
        private Bunifu.UI.WinForms.BunifuTextBox CountryBox;
        private Bunifu.UI.WinForms.BunifuLabel NationalIDLabel;
        private Bunifu.UI.WinForms.BunifuTextBox NationalIDBox;
        private Bunifu.UI.WinForms.BunifuDatePicker BirthdatePicker;
        private Bunifu.UI.WinForms.BunifuLabel BirthdateLabel;
        private Bunifu.UI.WinForms.BunifuLabel GenderOption2Label;
        private Bunifu.UI.WinForms.BunifuRadioButton GenderOption2;
        private Bunifu.UI.WinForms.BunifuLabel GenderOption1Label;
        private Bunifu.UI.WinForms.BunifuRadioButton GenderOption1;
        private Bunifu.UI.WinForms.BunifuLabel GenderLabel;
        private Bunifu.UI.WinForms.BunifuLabel PhoneNumberLabel;
        private Bunifu.UI.WinForms.BunifuTextBox PhoneNumberBox;
        private Bunifu.UI.WinForms.BunifuLabel EmailLabel;
        private Bunifu.UI.WinForms.BunifuTextBox EmailBox;
        private Bunifu.UI.WinForms.BunifuTextBox LastNameBox;
        private Bunifu.UI.WinForms.BunifuTextBox FirstNameBox;
    }
}