
namespace Azar_Hotel
{
    partial class AddOrdersForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddOrdersForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.Tab1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.GuestIDLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.GuestIDBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ProductIDLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.QuantityPLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.QuantityPBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PriceLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.PriceBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NameLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.NameBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ProductIDBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Tab2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabPage = new System.Windows.Forms.TabPage();
            this.QuantityOLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.QuantityOBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Pages = new Bunifu.UI.WinForms.BunifuPages();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.AddBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Title = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabPage2.SuspendLayout();
            this.tabPage.SuspendLayout();
            this.Pages.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // Tab1
            // 
            this.Tab1.AllowAnimations = true;
            this.Tab1.AllowMouseEffects = true;
            this.Tab1.AllowToggling = false;
            this.Tab1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.Tab1.AnimationSpeed = 200;
            this.Tab1.AutoGenerateColors = false;
            this.Tab1.AutoRoundBorders = false;
            this.Tab1.AutoSizeLeftIcon = true;
            this.Tab1.AutoSizeRightIcon = true;
            this.Tab1.BackColor = System.Drawing.Color.Transparent;
            this.Tab1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Tab1.BackgroundImage")));
            this.Tab1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.ButtonText = "Product";
            this.Tab1.ButtonTextMarginLeft = 0;
            this.Tab1.ColorContrastOnClick = 45;
            this.Tab1.ColorContrastOnHover = 45;
            this.Tab1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = false;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = false;
            this.Tab1.CustomizableEdges = borderEdges1;
            this.Tab1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Tab1.DisabledBorderColor = System.Drawing.Color.Indigo;
            this.Tab1.DisabledFillColor = System.Drawing.Color.Indigo;
            this.Tab1.DisabledForecolor = System.Drawing.Color.White;
            this.Tab1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Tab1.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Tab1.ForeColor = System.Drawing.Color.White;
            this.Tab1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Tab1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Tab1.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Tab1.IconMarginLeft = 11;
            this.Tab1.IconPadding = 10;
            this.Tab1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Tab1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Tab1.IconRightPadding = new System.Windows.Forms.Padding(15);
            this.Tab1.IconSize = 25;
            this.Tab1.IdleBorderColor = System.Drawing.Color.Indigo;
            this.Tab1.IdleBorderRadius = 50;
            this.Tab1.IdleBorderThickness = 1;
            this.Tab1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab1.IdleIconLeftImage = null;
            this.Tab1.IdleIconRightImage = null;
            this.Tab1.IndicateFocus = false;
            this.Tab1.Location = new System.Drawing.Point(131, 50);
            this.Tab1.Name = "Tab1";
            this.Tab1.OnDisabledState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab1.OnDisabledState.BorderRadius = 50;
            this.Tab1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.OnDisabledState.BorderThickness = 1;
            this.Tab1.OnDisabledState.FillColor = System.Drawing.Color.Indigo;
            this.Tab1.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.Tab1.OnDisabledState.IconLeftImage = null;
            this.Tab1.OnDisabledState.IconRightImage = null;
            this.Tab1.onHoverState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab1.onHoverState.BorderRadius = 50;
            this.Tab1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.onHoverState.BorderThickness = 1;
            this.Tab1.onHoverState.FillColor = System.Drawing.Color.BlueViolet;
            this.Tab1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Tab1.onHoverState.IconLeftImage = null;
            this.Tab1.onHoverState.IconRightImage = null;
            this.Tab1.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab1.OnIdleState.BorderRadius = 50;
            this.Tab1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.OnIdleState.BorderThickness = 1;
            this.Tab1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Tab1.OnIdleState.IconLeftImage = null;
            this.Tab1.OnIdleState.IconRightImage = null;
            this.Tab1.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab1.OnPressedState.BorderRadius = 50;
            this.Tab1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.OnPressedState.BorderThickness = 1;
            this.Tab1.OnPressedState.FillColor = System.Drawing.Color.Indigo;
            this.Tab1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Tab1.OnPressedState.IconLeftImage = null;
            this.Tab1.OnPressedState.IconRightImage = null;
            this.Tab1.Size = new System.Drawing.Size(125, 50);
            this.Tab1.TabIndex = 17;
            this.Tab1.TabStop = false;
            this.Tab1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Tab1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Tab1.TextMarginLeft = 0;
            this.Tab1.TextPadding = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.Tab1.UseDefaultRadiusAndThickness = true;
            this.Tab1.Click += new System.EventHandler(this.Tab1_Click);
            // 
            // GuestIDLabel
            // 
            this.GuestIDLabel.AllowParentOverrides = false;
            this.GuestIDLabel.AutoEllipsis = false;
            this.GuestIDLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.GuestIDLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.GuestIDLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.GuestIDLabel.ForeColor = System.Drawing.Color.Indigo;
            this.GuestIDLabel.Location = new System.Drawing.Point(250, 19);
            this.GuestIDLabel.Name = "GuestIDLabel";
            this.GuestIDLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.GuestIDLabel.Size = new System.Drawing.Size(46, 15);
            this.GuestIDLabel.TabIndex = 17;
            this.GuestIDLabel.Text = "Guest ID";
            this.GuestIDLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.GuestIDLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.GuestIDLabel.Visible = false;
            // 
            // GuestIDBox
            // 
            this.GuestIDBox.AcceptsReturn = false;
            this.GuestIDBox.AcceptsTab = false;
            this.GuestIDBox.AnimationSpeed = 200;
            this.GuestIDBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.GuestIDBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.GuestIDBox.BackColor = System.Drawing.Color.White;
            this.GuestIDBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("GuestIDBox.BackgroundImage")));
            this.GuestIDBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.GuestIDBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.GuestIDBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.GuestIDBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.GuestIDBox.BorderRadius = 7;
            this.GuestIDBox.BorderThickness = 3;
            this.GuestIDBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.GuestIDBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.GuestIDBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.GuestIDBox.DefaultText = "";
            this.GuestIDBox.FillColor = System.Drawing.Color.White;
            this.GuestIDBox.HideSelection = true;
            this.GuestIDBox.IconLeft = null;
            this.GuestIDBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.GuestIDBox.IconPadding = 15;
            this.GuestIDBox.IconRight = null;
            this.GuestIDBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.GuestIDBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.GuestIDBox.Lines = new string[0];
            this.GuestIDBox.Location = new System.Drawing.Point(250, 25);
            this.GuestIDBox.MaxLength = 20;
            this.GuestIDBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.GuestIDBox.Modified = false;
            this.GuestIDBox.Multiline = false;
            this.GuestIDBox.Name = "GuestIDBox";
            stateProperties1.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.GuestIDBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Gray;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.GuestIDBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties3.FillColor = System.Drawing.Color.White;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.GuestIDBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Indigo;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.GuestIDBox.OnIdleState = stateProperties4;
            this.GuestIDBox.Padding = new System.Windows.Forms.Padding(3);
            this.GuestIDBox.PasswordChar = '\0';
            this.GuestIDBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.GuestIDBox.PlaceholderText = "Guest ID";
            this.GuestIDBox.ReadOnly = false;
            this.GuestIDBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.GuestIDBox.SelectedText = "";
            this.GuestIDBox.SelectionLength = 0;
            this.GuestIDBox.SelectionStart = 0;
            this.GuestIDBox.ShortcutsEnabled = true;
            this.GuestIDBox.Size = new System.Drawing.Size(200, 50);
            this.GuestIDBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.GuestIDBox.TabIndex = 1;
            this.GuestIDBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.GuestIDBox.TextMarginBottom = 0;
            this.GuestIDBox.TextMarginLeft = 10;
            this.GuestIDBox.TextMarginTop = 0;
            this.GuestIDBox.TextPlaceholder = "Guest ID";
            this.GuestIDBox.UseSystemPasswordChar = false;
            this.GuestIDBox.WordWrap = true;
            this.GuestIDBox.TextChanged += new System.EventHandler(this.GuestIDBox_TextChanged);
            // 
            // ProductIDLabel
            // 
            this.ProductIDLabel.AllowParentOverrides = false;
            this.ProductIDLabel.AutoEllipsis = false;
            this.ProductIDLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.ProductIDLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.ProductIDLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.ProductIDLabel.ForeColor = System.Drawing.Color.Indigo;
            this.ProductIDLabel.Location = new System.Drawing.Point(22, 19);
            this.ProductIDLabel.Name = "ProductIDLabel";
            this.ProductIDLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ProductIDLabel.Size = new System.Drawing.Size(57, 15);
            this.ProductIDLabel.TabIndex = 13;
            this.ProductIDLabel.Text = "Product ID";
            this.ProductIDLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ProductIDLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.ProductIDLabel.Visible = false;
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.SystemColors.Control;
            this.tabPage2.Controls.Add(this.QuantityPLabel);
            this.tabPage2.Controls.Add(this.QuantityPBox);
            this.tabPage2.Controls.Add(this.PriceLabel);
            this.tabPage2.Controls.Add(this.PriceBox);
            this.tabPage2.Controls.Add(this.NameLabel);
            this.tabPage2.Controls.Add(this.NameBox);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(468, 138);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            // 
            // QuantityPLabel
            // 
            this.QuantityPLabel.AllowParentOverrides = false;
            this.QuantityPLabel.AutoEllipsis = false;
            this.QuantityPLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.QuantityPLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.QuantityPLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.QuantityPLabel.ForeColor = System.Drawing.Color.Indigo;
            this.QuantityPLabel.Location = new System.Drawing.Point(22, 94);
            this.QuantityPLabel.Name = "QuantityPLabel";
            this.QuantityPLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.QuantityPLabel.Size = new System.Drawing.Size(48, 15);
            this.QuantityPLabel.TabIndex = 39;
            this.QuantityPLabel.TabStop = false;
            this.QuantityPLabel.Text = "Quantity";
            this.QuantityPLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.QuantityPLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.QuantityPLabel.Visible = false;
            // 
            // QuantityPBox
            // 
            this.QuantityPBox.AcceptsReturn = false;
            this.QuantityPBox.AcceptsTab = false;
            this.QuantityPBox.AnimationSpeed = 200;
            this.QuantityPBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.QuantityPBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.QuantityPBox.BackColor = System.Drawing.Color.White;
            this.QuantityPBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("QuantityPBox.BackgroundImage")));
            this.QuantityPBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.QuantityPBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.QuantityPBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.QuantityPBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.QuantityPBox.BorderRadius = 7;
            this.QuantityPBox.BorderThickness = 3;
            this.QuantityPBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.QuantityPBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityPBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.QuantityPBox.DefaultText = "";
            this.QuantityPBox.FillColor = System.Drawing.Color.White;
            this.QuantityPBox.HideSelection = true;
            this.QuantityPBox.IconLeft = null;
            this.QuantityPBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityPBox.IconPadding = 15;
            this.QuantityPBox.IconRight = null;
            this.QuantityPBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityPBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.QuantityPBox.Lines = new string[0];
            this.QuantityPBox.Location = new System.Drawing.Point(22, 94);
            this.QuantityPBox.MaxLength = 20;
            this.QuantityPBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.QuantityPBox.Modified = false;
            this.QuantityPBox.Multiline = false;
            this.QuantityPBox.Name = "QuantityPBox";
            stateProperties5.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties5.FillColor = System.Drawing.Color.White;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityPBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Gray;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.QuantityPBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties7.FillColor = System.Drawing.Color.White;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityPBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Indigo;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityPBox.OnIdleState = stateProperties8;
            this.QuantityPBox.Padding = new System.Windows.Forms.Padding(3);
            this.QuantityPBox.PasswordChar = '\0';
            this.QuantityPBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.QuantityPBox.PlaceholderText = "Quantity";
            this.QuantityPBox.ReadOnly = false;
            this.QuantityPBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.QuantityPBox.SelectedText = "";
            this.QuantityPBox.SelectionLength = 0;
            this.QuantityPBox.SelectionStart = 0;
            this.QuantityPBox.ShortcutsEnabled = true;
            this.QuantityPBox.Size = new System.Drawing.Size(428, 50);
            this.QuantityPBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.QuantityPBox.TabIndex = 2;
            this.QuantityPBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.QuantityPBox.TextMarginBottom = 0;
            this.QuantityPBox.TextMarginLeft = 10;
            this.QuantityPBox.TextMarginTop = 0;
            this.QuantityPBox.TextPlaceholder = "Quantity";
            this.QuantityPBox.UseSystemPasswordChar = false;
            this.QuantityPBox.WordWrap = true;
            this.QuantityPBox.TextChanged += new System.EventHandler(this.QuantityPBox_TextChanged);
            // 
            // PriceLabel
            // 
            this.PriceLabel.AllowParentOverrides = false;
            this.PriceLabel.AutoEllipsis = false;
            this.PriceLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.PriceLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.PriceLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.PriceLabel.ForeColor = System.Drawing.Color.Indigo;
            this.PriceLabel.Location = new System.Drawing.Point(250, 19);
            this.PriceLabel.Name = "PriceLabel";
            this.PriceLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.PriceLabel.Size = new System.Drawing.Size(27, 15);
            this.PriceLabel.TabIndex = 37;
            this.PriceLabel.TabStop = false;
            this.PriceLabel.Text = "Price";
            this.PriceLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.PriceLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.PriceLabel.Visible = false;
            // 
            // PriceBox
            // 
            this.PriceBox.AcceptsReturn = false;
            this.PriceBox.AcceptsTab = false;
            this.PriceBox.AnimationSpeed = 200;
            this.PriceBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PriceBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PriceBox.BackColor = System.Drawing.Color.White;
            this.PriceBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PriceBox.BackgroundImage")));
            this.PriceBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.PriceBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.PriceBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.PriceBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.PriceBox.BorderRadius = 7;
            this.PriceBox.BorderThickness = 3;
            this.PriceBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PriceBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PriceBox.DefaultText = "";
            this.PriceBox.FillColor = System.Drawing.Color.White;
            this.PriceBox.HideSelection = true;
            this.PriceBox.IconLeft = null;
            this.PriceBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.IconPadding = 15;
            this.PriceBox.IconRight = null;
            this.PriceBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.PriceBox.Lines = new string[0];
            this.PriceBox.Location = new System.Drawing.Point(250, 25);
            this.PriceBox.MaxLength = 20;
            this.PriceBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PriceBox.Modified = false;
            this.PriceBox.Multiline = false;
            this.PriceBox.Name = "PriceBox";
            stateProperties9.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties9.FillColor = System.Drawing.Color.White;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Gray;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PriceBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties11.FillColor = System.Drawing.Color.White;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Indigo;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnIdleState = stateProperties12;
            this.PriceBox.Padding = new System.Windows.Forms.Padding(3);
            this.PriceBox.PasswordChar = '\0';
            this.PriceBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.PriceBox.PlaceholderText = "Price";
            this.PriceBox.ReadOnly = false;
            this.PriceBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PriceBox.SelectedText = "";
            this.PriceBox.SelectionLength = 0;
            this.PriceBox.SelectionStart = 0;
            this.PriceBox.ShortcutsEnabled = true;
            this.PriceBox.Size = new System.Drawing.Size(200, 50);
            this.PriceBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.PriceBox.TabIndex = 1;
            this.PriceBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PriceBox.TextMarginBottom = 0;
            this.PriceBox.TextMarginLeft = 10;
            this.PriceBox.TextMarginTop = 0;
            this.PriceBox.TextPlaceholder = "Price";
            this.PriceBox.UseSystemPasswordChar = false;
            this.PriceBox.WordWrap = true;
            this.PriceBox.TextChanged += new System.EventHandler(this.PriceBox_TextChanged);
            // 
            // NameLabel
            // 
            this.NameLabel.AllowParentOverrides = false;
            this.NameLabel.AutoEllipsis = false;
            this.NameLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.NameLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.NameLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.NameLabel.ForeColor = System.Drawing.Color.Indigo;
            this.NameLabel.Location = new System.Drawing.Point(22, 19);
            this.NameLabel.Name = "NameLabel";
            this.NameLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.NameLabel.Size = new System.Drawing.Size(33, 15);
            this.NameLabel.TabIndex = 36;
            this.NameLabel.TabStop = false;
            this.NameLabel.Text = "Name";
            this.NameLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.NameLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.NameLabel.Visible = false;
            // 
            // NameBox
            // 
            this.NameBox.AcceptsReturn = false;
            this.NameBox.AcceptsTab = false;
            this.NameBox.AnimationSpeed = 200;
            this.NameBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NameBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NameBox.BackColor = System.Drawing.Color.White;
            this.NameBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NameBox.BackgroundImage")));
            this.NameBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.NameBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.NameBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.NameBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.NameBox.BorderRadius = 7;
            this.NameBox.BorderThickness = 3;
            this.NameBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NameBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NameBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NameBox.DefaultText = "";
            this.NameBox.FillColor = System.Drawing.Color.White;
            this.NameBox.HideSelection = true;
            this.NameBox.IconLeft = null;
            this.NameBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameBox.IconPadding = 15;
            this.NameBox.IconRight = null;
            this.NameBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.NameBox.Lines = new string[0];
            this.NameBox.Location = new System.Drawing.Point(22, 25);
            this.NameBox.MaxLength = 20;
            this.NameBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.NameBox.Modified = false;
            this.NameBox.Multiline = false;
            this.NameBox.Name = "NameBox";
            stateProperties13.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties13.FillColor = System.Drawing.Color.White;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Gray;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NameBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties15.FillColor = System.Drawing.Color.White;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Indigo;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameBox.OnIdleState = stateProperties16;
            this.NameBox.Padding = new System.Windows.Forms.Padding(3);
            this.NameBox.PasswordChar = '\0';
            this.NameBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.NameBox.PlaceholderText = "Name";
            this.NameBox.ReadOnly = false;
            this.NameBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NameBox.SelectedText = "";
            this.NameBox.SelectionLength = 0;
            this.NameBox.SelectionStart = 0;
            this.NameBox.ShortcutsEnabled = true;
            this.NameBox.Size = new System.Drawing.Size(200, 50);
            this.NameBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.NameBox.TabIndex = 0;
            this.NameBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NameBox.TextMarginBottom = 0;
            this.NameBox.TextMarginLeft = 10;
            this.NameBox.TextMarginTop = 0;
            this.NameBox.TextPlaceholder = "Name";
            this.NameBox.UseSystemPasswordChar = false;
            this.NameBox.WordWrap = true;
            this.NameBox.TextChanged += new System.EventHandler(this.NameBox_TextChanged);
            // 
            // ProductIDBox
            // 
            this.ProductIDBox.AcceptsReturn = false;
            this.ProductIDBox.AcceptsTab = false;
            this.ProductIDBox.AnimationSpeed = 200;
            this.ProductIDBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ProductIDBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ProductIDBox.BackColor = System.Drawing.Color.White;
            this.ProductIDBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProductIDBox.BackgroundImage")));
            this.ProductIDBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.ProductIDBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.ProductIDBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.ProductIDBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.ProductIDBox.BorderRadius = 7;
            this.ProductIDBox.BorderThickness = 3;
            this.ProductIDBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ProductIDBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductIDBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ProductIDBox.DefaultText = "";
            this.ProductIDBox.FillColor = System.Drawing.Color.White;
            this.ProductIDBox.HideSelection = true;
            this.ProductIDBox.IconLeft = null;
            this.ProductIDBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductIDBox.IconPadding = 15;
            this.ProductIDBox.IconRight = null;
            this.ProductIDBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductIDBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.ProductIDBox.Lines = new string[0];
            this.ProductIDBox.Location = new System.Drawing.Point(22, 25);
            this.ProductIDBox.MaxLength = 20;
            this.ProductIDBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.ProductIDBox.Modified = false;
            this.ProductIDBox.Multiline = false;
            this.ProductIDBox.Name = "ProductIDBox";
            stateProperties17.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties17.FillColor = System.Drawing.Color.White;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductIDBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Gray;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ProductIDBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties19.FillColor = System.Drawing.Color.White;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductIDBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Indigo;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductIDBox.OnIdleState = stateProperties20;
            this.ProductIDBox.Padding = new System.Windows.Forms.Padding(3);
            this.ProductIDBox.PasswordChar = '\0';
            this.ProductIDBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.ProductIDBox.PlaceholderText = "Product ID";
            this.ProductIDBox.ReadOnly = false;
            this.ProductIDBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ProductIDBox.SelectedText = "";
            this.ProductIDBox.SelectionLength = 0;
            this.ProductIDBox.SelectionStart = 0;
            this.ProductIDBox.ShortcutsEnabled = true;
            this.ProductIDBox.Size = new System.Drawing.Size(200, 50);
            this.ProductIDBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.ProductIDBox.TabIndex = 0;
            this.ProductIDBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProductIDBox.TextMarginBottom = 0;
            this.ProductIDBox.TextMarginLeft = 10;
            this.ProductIDBox.TextMarginTop = 0;
            this.ProductIDBox.TextPlaceholder = "Product ID";
            this.ProductIDBox.UseSystemPasswordChar = false;
            this.ProductIDBox.WordWrap = true;
            this.ProductIDBox.TextChanged += new System.EventHandler(this.ProductIDBox_TextChanged);
            // 
            // Tab2
            // 
            this.Tab2.AllowAnimations = true;
            this.Tab2.AllowMouseEffects = true;
            this.Tab2.AllowToggling = false;
            this.Tab2.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.Tab2.AnimationSpeed = 200;
            this.Tab2.AutoGenerateColors = false;
            this.Tab2.AutoRoundBorders = false;
            this.Tab2.AutoSizeLeftIcon = true;
            this.Tab2.AutoSizeRightIcon = true;
            this.Tab2.BackColor = System.Drawing.Color.Transparent;
            this.Tab2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Tab2.BackgroundImage")));
            this.Tab2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.ButtonText = "Order";
            this.Tab2.ButtonTextMarginLeft = 0;
            this.Tab2.ColorContrastOnClick = 45;
            this.Tab2.ColorContrastOnHover = 45;
            this.Tab2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = false;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = false;
            borderEdges2.TopRight = true;
            this.Tab2.CustomizableEdges = borderEdges2;
            this.Tab2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Tab2.DisabledBorderColor = System.Drawing.Color.Indigo;
            this.Tab2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.DisabledForecolor = System.Drawing.Color.White;
            this.Tab2.Enabled = false;
            this.Tab2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Tab2.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Tab2.ForeColor = System.Drawing.Color.White;
            this.Tab2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Tab2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Tab2.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Tab2.IconMarginLeft = 11;
            this.Tab2.IconPadding = 10;
            this.Tab2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Tab2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Tab2.IconRightPadding = new System.Windows.Forms.Padding(15);
            this.Tab2.IconSize = 25;
            this.Tab2.IdleBorderColor = System.Drawing.Color.Indigo;
            this.Tab2.IdleBorderRadius = 50;
            this.Tab2.IdleBorderThickness = 1;
            this.Tab2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.IdleIconLeftImage = null;
            this.Tab2.IdleIconRightImage = null;
            this.Tab2.IndicateFocus = false;
            this.Tab2.Location = new System.Drawing.Point(255, 50);
            this.Tab2.Name = "Tab2";
            this.Tab2.OnDisabledState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab2.OnDisabledState.BorderRadius = 50;
            this.Tab2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.OnDisabledState.BorderThickness = 1;
            this.Tab2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.Tab2.OnDisabledState.IconLeftImage = null;
            this.Tab2.OnDisabledState.IconRightImage = null;
            this.Tab2.onHoverState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab2.onHoverState.BorderRadius = 50;
            this.Tab2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.onHoverState.BorderThickness = 1;
            this.Tab2.onHoverState.FillColor = System.Drawing.Color.BlueViolet;
            this.Tab2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Tab2.onHoverState.IconLeftImage = null;
            this.Tab2.onHoverState.IconRightImage = null;
            this.Tab2.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab2.OnIdleState.BorderRadius = 50;
            this.Tab2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.OnIdleState.BorderThickness = 1;
            this.Tab2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Tab2.OnIdleState.IconLeftImage = null;
            this.Tab2.OnIdleState.IconRightImage = null;
            this.Tab2.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab2.OnPressedState.BorderRadius = 50;
            this.Tab2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.OnPressedState.BorderThickness = 1;
            this.Tab2.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.Tab2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Tab2.OnPressedState.IconLeftImage = null;
            this.Tab2.OnPressedState.IconRightImage = null;
            this.Tab2.Size = new System.Drawing.Size(125, 50);
            this.Tab2.TabIndex = 18;
            this.Tab2.TabStop = false;
            this.Tab2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Tab2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Tab2.TextMarginLeft = 0;
            this.Tab2.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.Tab2.UseDefaultRadiusAndThickness = true;
            this.Tab2.Click += new System.EventHandler(this.Tab2_Click);
            // 
            // tabPage
            // 
            this.tabPage.BackColor = System.Drawing.SystemColors.Control;
            this.tabPage.Controls.Add(this.QuantityOLabel);
            this.tabPage.Controls.Add(this.QuantityOBox);
            this.tabPage.Controls.Add(this.GuestIDLabel);
            this.tabPage.Controls.Add(this.GuestIDBox);
            this.tabPage.Controls.Add(this.ProductIDLabel);
            this.tabPage.Controls.Add(this.ProductIDBox);
            this.tabPage.Location = new System.Drawing.Point(4, 4);
            this.tabPage.Name = "tabPage";
            this.tabPage.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage.Size = new System.Drawing.Size(468, 138);
            this.tabPage.TabIndex = 0;
            this.tabPage.Text = "tabPage1";
            // 
            // QuantityOLabel
            // 
            this.QuantityOLabel.AllowParentOverrides = false;
            this.QuantityOLabel.AutoEllipsis = false;
            this.QuantityOLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.QuantityOLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.QuantityOLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.QuantityOLabel.ForeColor = System.Drawing.Color.Indigo;
            this.QuantityOLabel.Location = new System.Drawing.Point(22, 94);
            this.QuantityOLabel.Name = "QuantityOLabel";
            this.QuantityOLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.QuantityOLabel.Size = new System.Drawing.Size(48, 15);
            this.QuantityOLabel.TabIndex = 33;
            this.QuantityOLabel.TabStop = false;
            this.QuantityOLabel.Text = "Quantity";
            this.QuantityOLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.QuantityOLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.QuantityOLabel.Visible = false;
            // 
            // QuantityOBox
            // 
            this.QuantityOBox.AcceptsReturn = false;
            this.QuantityOBox.AcceptsTab = false;
            this.QuantityOBox.AnimationSpeed = 200;
            this.QuantityOBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.QuantityOBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.QuantityOBox.BackColor = System.Drawing.Color.White;
            this.QuantityOBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("QuantityOBox.BackgroundImage")));
            this.QuantityOBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.QuantityOBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.QuantityOBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.QuantityOBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.QuantityOBox.BorderRadius = 7;
            this.QuantityOBox.BorderThickness = 3;
            this.QuantityOBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.QuantityOBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityOBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.QuantityOBox.DefaultText = "";
            this.QuantityOBox.FillColor = System.Drawing.Color.White;
            this.QuantityOBox.HideSelection = true;
            this.QuantityOBox.IconLeft = null;
            this.QuantityOBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityOBox.IconPadding = 15;
            this.QuantityOBox.IconRight = null;
            this.QuantityOBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityOBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.QuantityOBox.Lines = new string[0];
            this.QuantityOBox.Location = new System.Drawing.Point(22, 94);
            this.QuantityOBox.MaxLength = 20;
            this.QuantityOBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.QuantityOBox.Modified = false;
            this.QuantityOBox.Multiline = false;
            this.QuantityOBox.Name = "QuantityOBox";
            stateProperties21.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties21.FillColor = System.Drawing.Color.White;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityOBox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Gray;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.QuantityOBox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties23.FillColor = System.Drawing.Color.White;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityOBox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Indigo;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityOBox.OnIdleState = stateProperties24;
            this.QuantityOBox.Padding = new System.Windows.Forms.Padding(3);
            this.QuantityOBox.PasswordChar = '\0';
            this.QuantityOBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.QuantityOBox.PlaceholderText = "Quantity";
            this.QuantityOBox.ReadOnly = false;
            this.QuantityOBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.QuantityOBox.SelectedText = "";
            this.QuantityOBox.SelectionLength = 0;
            this.QuantityOBox.SelectionStart = 0;
            this.QuantityOBox.ShortcutsEnabled = true;
            this.QuantityOBox.Size = new System.Drawing.Size(428, 50);
            this.QuantityOBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.QuantityOBox.TabIndex = 2;
            this.QuantityOBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.QuantityOBox.TextMarginBottom = 0;
            this.QuantityOBox.TextMarginLeft = 10;
            this.QuantityOBox.TextMarginTop = 0;
            this.QuantityOBox.TextPlaceholder = "Quantity";
            this.QuantityOBox.UseSystemPasswordChar = false;
            this.QuantityOBox.WordWrap = true;
            this.QuantityOBox.TextChanged += new System.EventHandler(this.QuantityOBox_TextChanged);
            // 
            // Pages
            // 
            this.Pages.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.Pages.AllowTransitions = true;
            this.Pages.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.Pages.Controls.Add(this.tabPage);
            this.Pages.Controls.Add(this.tabPage2);
            this.Pages.Location = new System.Drawing.Point(12, 106);
            this.Pages.Multiline = true;
            this.Pages.Name = "Pages";
            this.Pages.Page = this.tabPage2;
            this.Pages.PageIndex = 1;
            this.Pages.PageName = "tabPage2";
            this.Pages.PageTitle = "tabPage2";
            this.Pages.SelectedIndex = 0;
            this.Pages.Size = new System.Drawing.Size(476, 164);
            this.Pages.TabIndex = 19;
            this.Pages.TabStop = false;
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.Pages.Transition = animation1;
            this.Pages.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(53)))), ((int)(((byte)(163)))));
            this.bunifuPanel1.BorderRadius = 10;
            this.bunifuPanel1.BorderThickness = 7;
            this.bunifuPanel1.Controls.Add(this.Pages);
            this.bunifuPanel1.Controls.Add(this.Tab2);
            this.bunifuPanel1.Controls.Add(this.Tab1);
            this.bunifuPanel1.Controls.Add(this.AddBt);
            this.bunifuPanel1.Controls.Add(this.panel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(500, 350);
            this.bunifuPanel1.TabIndex = 4;
            // 
            // AddBt
            // 
            this.AddBt.AllowAnimations = true;
            this.AddBt.AllowMouseEffects = true;
            this.AddBt.AllowToggling = false;
            this.AddBt.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.AddBt.AnimationSpeed = 200;
            this.AddBt.AutoGenerateColors = false;
            this.AddBt.AutoRoundBorders = false;
            this.AddBt.AutoSizeLeftIcon = true;
            this.AddBt.AutoSizeRightIcon = true;
            this.AddBt.BackColor = System.Drawing.Color.Transparent;
            this.AddBt.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddBt.BackgroundImage")));
            this.AddBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.ButtonText = "Add";
            this.AddBt.ButtonTextMarginLeft = 0;
            this.AddBt.ColorContrastOnClick = 45;
            this.AddBt.ColorContrastOnHover = 45;
            this.AddBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AddBt.CustomizableEdges = borderEdges3;
            this.AddBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddBt.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AddBt.ForeColor = System.Drawing.Color.White;
            this.AddBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddBt.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.AddBt.IconMarginLeft = 11;
            this.AddBt.IconPadding = 10;
            this.AddBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddBt.IconRightPadding = new System.Windows.Forms.Padding(15);
            this.AddBt.IconSize = 25;
            this.AddBt.IdleBorderColor = System.Drawing.Color.Transparent;
            this.AddBt.IdleBorderRadius = 7;
            this.AddBt.IdleBorderThickness = 1;
            this.AddBt.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.IdleIconLeftImage = null;
            this.AddBt.IdleIconRightImage = null;
            this.AddBt.IndicateFocus = false;
            this.AddBt.Location = new System.Drawing.Point(35, 276);
            this.AddBt.Name = "AddBt";
            this.AddBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddBt.OnDisabledState.BorderRadius = 7;
            this.AddBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnDisabledState.BorderThickness = 1;
            this.AddBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddBt.OnDisabledState.IconLeftImage = null;
            this.AddBt.OnDisabledState.IconRightImage = null;
            this.AddBt.onHoverState.BorderColor = System.Drawing.Color.BlueViolet;
            this.AddBt.onHoverState.BorderRadius = 7;
            this.AddBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.onHoverState.BorderThickness = 1;
            this.AddBt.onHoverState.FillColor = System.Drawing.Color.BlueViolet;
            this.AddBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddBt.onHoverState.IconLeftImage = null;
            this.AddBt.onHoverState.IconRightImage = null;
            this.AddBt.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.AddBt.OnIdleState.BorderRadius = 7;
            this.AddBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnIdleState.BorderThickness = 1;
            this.AddBt.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AddBt.OnIdleState.IconLeftImage = null;
            this.AddBt.OnIdleState.IconRightImage = null;
            this.AddBt.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.AddBt.OnPressedState.BorderRadius = 7;
            this.AddBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnPressedState.BorderThickness = 1;
            this.AddBt.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.AddBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddBt.OnPressedState.IconLeftImage = null;
            this.AddBt.OnPressedState.IconRightImage = null;
            this.AddBt.Size = new System.Drawing.Size(428, 50);
            this.AddBt.TabIndex = 5;
            this.AddBt.TabStop = false;
            this.AddBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddBt.TextMarginLeft = 0;
            this.AddBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddBt.UseDefaultRadiusAndThickness = true;
            this.AddBt.Click += new System.EventHandler(this.AddBt_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(53)))), ((int)(((byte)(163)))));
            this.panel1.Controls.Add(this.btClose);
            this.panel1.Controls.Add(this.Title);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(500, 40);
            this.panel1.TabIndex = 11;
            // 
            // btClose
            // 
            this.btClose.AllowAnimations = true;
            this.btClose.AllowMouseEffects = true;
            this.btClose.AllowToggling = false;
            this.btClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btClose.AnimationSpeed = 200;
            this.btClose.AutoGenerateColors = false;
            this.btClose.AutoRoundBorders = false;
            this.btClose.AutoSizeLeftIcon = true;
            this.btClose.AutoSizeRightIcon = true;
            this.btClose.BackColor = System.Drawing.Color.Transparent;
            this.btClose.BackColor1 = System.Drawing.Color.Transparent;
            this.btClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btClose.BackgroundImage")));
            this.btClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.ButtonText = "";
            this.btClose.ButtonTextMarginLeft = 0;
            this.btClose.ColorContrastOnClick = 45;
            this.btClose.ColorContrastOnHover = 45;
            this.btClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btClose.CustomizableEdges = borderEdges4;
            this.btClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btClose.ForeColor = System.Drawing.Color.Transparent;
            this.btClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btClose.IconLeftPadding = new System.Windows.Forms.Padding(4);
            this.btClose.IconMarginLeft = 11;
            this.btClose.IconPadding = 5;
            this.btClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btClose.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btClose.IconSize = 25;
            this.btClose.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btClose.IdleBorderRadius = 3;
            this.btClose.IdleBorderThickness = 1;
            this.btClose.IdleFillColor = System.Drawing.Color.Transparent;
            this.btClose.IdleIconLeftImage = global::Azar_Hotel.Properties.Resources.close;
            this.btClose.IdleIconRightImage = null;
            this.btClose.IndicateFocus = false;
            this.btClose.Location = new System.Drawing.Point(469, 6);
            this.btClose.Name = "btClose";
            this.btClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btClose.OnDisabledState.BorderRadius = 3;
            this.btClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnDisabledState.BorderThickness = 1;
            this.btClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btClose.OnDisabledState.IconLeftImage = null;
            this.btClose.OnDisabledState.IconRightImage = null;
            this.btClose.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.btClose.onHoverState.BorderRadius = 3;
            this.btClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.onHoverState.BorderThickness = 1;
            this.btClose.onHoverState.FillColor = System.Drawing.Color.Red;
            this.btClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btClose.onHoverState.IconLeftImage = null;
            this.btClose.onHoverState.IconRightImage = null;
            this.btClose.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.BorderRadius = 3;
            this.btClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnIdleState.BorderThickness = 1;
            this.btClose.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.IconLeftImage = global::Azar_Hotel.Properties.Resources.close;
            this.btClose.OnIdleState.IconRightImage = null;
            this.btClose.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.btClose.OnPressedState.BorderRadius = 3;
            this.btClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnPressedState.BorderThickness = 1;
            this.btClose.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.btClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btClose.OnPressedState.IconLeftImage = null;
            this.btClose.OnPressedState.IconRightImage = null;
            this.btClose.Size = new System.Drawing.Size(25, 25);
            this.btClose.TabIndex = 13;
            this.btClose.TabStop = false;
            this.btClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btClose.TextMarginLeft = 0;
            this.btClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btClose.UseDefaultRadiusAndThickness = true;
            this.btClose.Click += new System.EventHandler(this.btClose_Click);
            // 
            // Title
            // 
            this.Title.AllowParentOverrides = false;
            this.Title.AutoEllipsis = false;
            this.Title.AutoSize = false;
            this.Title.Cursor = System.Windows.Forms.Cursors.Default;
            this.Title.CursorType = System.Windows.Forms.Cursors.Default;
            this.Title.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Title.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold);
            this.Title.ForeColor = System.Drawing.Color.White;
            this.Title.Location = new System.Drawing.Point(0, 0);
            this.Title.Name = "Title";
            this.Title.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Title.Size = new System.Drawing.Size(500, 40);
            this.Title.TabIndex = 0;
            this.Title.Text = "Add";
            this.Title.TextAlignment = System.Drawing.ContentAlignment.BottomCenter;
            this.Title.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.Title.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form_MouseDown);
            // 
            // AddOrdersForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(500, 350);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AddOrdersForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "AddOrdersForm";
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.tabPage.ResumeLayout(false);
            this.tabPage.PerformLayout();
            this.Pages.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Tab1;
        private Bunifu.UI.WinForms.BunifuLabel GuestIDLabel;
        private Bunifu.UI.WinForms.BunifuTextBox GuestIDBox;
        private Bunifu.UI.WinForms.BunifuLabel ProductIDLabel;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuTextBox ProductIDBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Tab2;
        private System.Windows.Forms.TabPage tabPage;
        private Bunifu.UI.WinForms.BunifuTextBox QuantityOBox;
        private Bunifu.UI.WinForms.BunifuPages Pages;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AddBt;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btClose;
        private Bunifu.UI.WinForms.BunifuLabel Title;
        private Bunifu.UI.WinForms.BunifuLabel QuantityPLabel;
        private Bunifu.UI.WinForms.BunifuTextBox QuantityPBox;
        private Bunifu.UI.WinForms.BunifuLabel PriceLabel;
        private Bunifu.UI.WinForms.BunifuTextBox PriceBox;
        private Bunifu.UI.WinForms.BunifuLabel NameLabel;
        private Bunifu.UI.WinForms.BunifuTextBox NameBox;
        private Bunifu.UI.WinForms.BunifuLabel QuantityOLabel;
    }
}