
namespace Azar_Hotel
{
    partial class AddRoomsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddRoomsForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.Title = new Bunifu.UI.WinForms.BunifuLabel();
            this.AddBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.Pages = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage = new System.Windows.Forms.TabPage();
            this.ContractDatePicker = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.ContractdateLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.ExpirdatePicker = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.ExpirdateLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.GuestIDLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.GuestIDBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.RoomIDLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.RoomIDBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.RoomTypeLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.PriceLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.PriceBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.FloorLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.FloorBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SectionLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.SectionBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.RoomTypeBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.RoomNumberLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.RoomNumberBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Tab2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Tab1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.Pages.SuspendLayout();
            this.tabPage.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // Title
            // 
            this.Title.AllowParentOverrides = false;
            this.Title.AutoEllipsis = false;
            this.Title.AutoSize = false;
            this.Title.Cursor = System.Windows.Forms.Cursors.Default;
            this.Title.CursorType = System.Windows.Forms.Cursors.Default;
            this.Title.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Title.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold);
            this.Title.ForeColor = System.Drawing.Color.White;
            this.Title.Location = new System.Drawing.Point(0, 0);
            this.Title.Name = "Title";
            this.Title.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Title.Size = new System.Drawing.Size(500, 40);
            this.Title.TabIndex = 0;
            this.Title.Text = "Add";
            this.Title.TextAlignment = System.Drawing.ContentAlignment.BottomCenter;
            this.Title.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.Title.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form_MouseDown);
            // 
            // AddBt
            // 
            this.AddBt.AllowAnimations = true;
            this.AddBt.AllowMouseEffects = true;
            this.AddBt.AllowToggling = false;
            this.AddBt.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.AddBt.AnimationSpeed = 200;
            this.AddBt.AutoGenerateColors = false;
            this.AddBt.AutoRoundBorders = false;
            this.AddBt.AutoSizeLeftIcon = true;
            this.AddBt.AutoSizeRightIcon = true;
            this.AddBt.BackColor = System.Drawing.Color.Transparent;
            this.AddBt.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddBt.BackgroundImage")));
            this.AddBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.ButtonText = "Add";
            this.AddBt.ButtonTextMarginLeft = 0;
            this.AddBt.ColorContrastOnClick = 45;
            this.AddBt.ColorContrastOnHover = 45;
            this.AddBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AddBt.CustomizableEdges = borderEdges1;
            this.AddBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddBt.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AddBt.ForeColor = System.Drawing.Color.White;
            this.AddBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddBt.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.AddBt.IconMarginLeft = 11;
            this.AddBt.IconPadding = 10;
            this.AddBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddBt.IconRightPadding = new System.Windows.Forms.Padding(15);
            this.AddBt.IconSize = 25;
            this.AddBt.IdleBorderColor = System.Drawing.Color.Transparent;
            this.AddBt.IdleBorderRadius = 7;
            this.AddBt.IdleBorderThickness = 1;
            this.AddBt.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.IdleIconLeftImage = null;
            this.AddBt.IdleIconRightImage = null;
            this.AddBt.IndicateFocus = false;
            this.AddBt.Location = new System.Drawing.Point(35, 308);
            this.AddBt.Name = "AddBt";
            this.AddBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddBt.OnDisabledState.BorderRadius = 7;
            this.AddBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnDisabledState.BorderThickness = 1;
            this.AddBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddBt.OnDisabledState.IconLeftImage = null;
            this.AddBt.OnDisabledState.IconRightImage = null;
            this.AddBt.onHoverState.BorderColor = System.Drawing.Color.BlueViolet;
            this.AddBt.onHoverState.BorderRadius = 7;
            this.AddBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.onHoverState.BorderThickness = 1;
            this.AddBt.onHoverState.FillColor = System.Drawing.Color.BlueViolet;
            this.AddBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddBt.onHoverState.IconLeftImage = null;
            this.AddBt.onHoverState.IconRightImage = null;
            this.AddBt.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.AddBt.OnIdleState.BorderRadius = 7;
            this.AddBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnIdleState.BorderThickness = 1;
            this.AddBt.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(150)))));
            this.AddBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AddBt.OnIdleState.IconLeftImage = null;
            this.AddBt.OnIdleState.IconRightImage = null;
            this.AddBt.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.AddBt.OnPressedState.BorderRadius = 7;
            this.AddBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddBt.OnPressedState.BorderThickness = 1;
            this.AddBt.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.AddBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddBt.OnPressedState.IconLeftImage = null;
            this.AddBt.OnPressedState.IconRightImage = null;
            this.AddBt.Size = new System.Drawing.Size(428, 50);
            this.AddBt.TabIndex = 5;
            this.AddBt.TabStop = false;
            this.AddBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddBt.TextMarginLeft = 0;
            this.AddBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddBt.UseDefaultRadiusAndThickness = true;
            this.AddBt.Click += new System.EventHandler(this.AddBt_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(53)))), ((int)(((byte)(163)))));
            this.panel1.Controls.Add(this.btClose);
            this.panel1.Controls.Add(this.Title);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(500, 40);
            this.panel1.TabIndex = 11;
            // 
            // btClose
            // 
            this.btClose.AllowAnimations = true;
            this.btClose.AllowMouseEffects = true;
            this.btClose.AllowToggling = false;
            this.btClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btClose.AnimationSpeed = 200;
            this.btClose.AutoGenerateColors = false;
            this.btClose.AutoRoundBorders = false;
            this.btClose.AutoSizeLeftIcon = true;
            this.btClose.AutoSizeRightIcon = true;
            this.btClose.BackColor = System.Drawing.Color.Transparent;
            this.btClose.BackColor1 = System.Drawing.Color.Transparent;
            this.btClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btClose.BackgroundImage")));
            this.btClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.ButtonText = "";
            this.btClose.ButtonTextMarginLeft = 0;
            this.btClose.ColorContrastOnClick = 45;
            this.btClose.ColorContrastOnHover = 45;
            this.btClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btClose.CustomizableEdges = borderEdges2;
            this.btClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btClose.ForeColor = System.Drawing.Color.Transparent;
            this.btClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btClose.IconLeftPadding = new System.Windows.Forms.Padding(4);
            this.btClose.IconMarginLeft = 11;
            this.btClose.IconPadding = 5;
            this.btClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btClose.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btClose.IconSize = 25;
            this.btClose.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btClose.IdleBorderRadius = 3;
            this.btClose.IdleBorderThickness = 1;
            this.btClose.IdleFillColor = System.Drawing.Color.Transparent;
            this.btClose.IdleIconLeftImage = global::Azar_Hotel.Properties.Resources.close;
            this.btClose.IdleIconRightImage = null;
            this.btClose.IndicateFocus = false;
            this.btClose.Location = new System.Drawing.Point(469, 6);
            this.btClose.Name = "btClose";
            this.btClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btClose.OnDisabledState.BorderRadius = 3;
            this.btClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnDisabledState.BorderThickness = 1;
            this.btClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btClose.OnDisabledState.IconLeftImage = null;
            this.btClose.OnDisabledState.IconRightImage = null;
            this.btClose.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.btClose.onHoverState.BorderRadius = 3;
            this.btClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.onHoverState.BorderThickness = 1;
            this.btClose.onHoverState.FillColor = System.Drawing.Color.Red;
            this.btClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btClose.onHoverState.IconLeftImage = null;
            this.btClose.onHoverState.IconRightImage = null;
            this.btClose.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.BorderRadius = 3;
            this.btClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnIdleState.BorderThickness = 1;
            this.btClose.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btClose.OnIdleState.IconLeftImage = global::Azar_Hotel.Properties.Resources.close;
            this.btClose.OnIdleState.IconRightImage = null;
            this.btClose.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.btClose.OnPressedState.BorderRadius = 3;
            this.btClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btClose.OnPressedState.BorderThickness = 1;
            this.btClose.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.btClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btClose.OnPressedState.IconLeftImage = null;
            this.btClose.OnPressedState.IconRightImage = null;
            this.btClose.Size = new System.Drawing.Size(25, 25);
            this.btClose.TabIndex = 13;
            this.btClose.TabStop = false;
            this.btClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btClose.TextMarginLeft = 0;
            this.btClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btClose.UseDefaultRadiusAndThickness = true;
            this.btClose.Click += new System.EventHandler(this.btClose_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(53)))), ((int)(((byte)(163)))));
            this.bunifuPanel1.BorderRadius = 10;
            this.bunifuPanel1.BorderThickness = 7;
            this.bunifuPanel1.Controls.Add(this.Pages);
            this.bunifuPanel1.Controls.Add(this.Tab2);
            this.bunifuPanel1.Controls.Add(this.Tab1);
            this.bunifuPanel1.Controls.Add(this.AddBt);
            this.bunifuPanel1.Controls.Add(this.panel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(500, 382);
            this.bunifuPanel1.TabIndex = 3;
            // 
            // Pages
            // 
            this.Pages.Alignment = System.Windows.Forms.TabAlignment.Right;
            this.Pages.AllowTransitions = true;
            this.Pages.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.Pages.Controls.Add(this.tabPage);
            this.Pages.Controls.Add(this.tabPage2);
            this.Pages.Location = new System.Drawing.Point(12, 106);
            this.Pages.Multiline = true;
            this.Pages.Name = "Pages";
            this.Pages.Page = this.tabPage;
            this.Pages.PageIndex = 0;
            this.Pages.PageName = "tabPage";
            this.Pages.PageTitle = "tabPage1";
            this.Pages.SelectedIndex = 0;
            this.Pages.Size = new System.Drawing.Size(476, 196);
            this.Pages.TabIndex = 19;
            this.Pages.TabStop = false;
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.Pages.Transition = animation1;
            this.Pages.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // tabPage
            // 
            this.tabPage.BackColor = System.Drawing.SystemColors.Control;
            this.tabPage.Controls.Add(this.ContractDatePicker);
            this.tabPage.Controls.Add(this.ContractdateLabel);
            this.tabPage.Controls.Add(this.ExpirdatePicker);
            this.tabPage.Controls.Add(this.ExpirdateLabel);
            this.tabPage.Controls.Add(this.GuestIDLabel);
            this.tabPage.Controls.Add(this.GuestIDBox);
            this.tabPage.Controls.Add(this.RoomIDLabel);
            this.tabPage.Controls.Add(this.RoomIDBox);
            this.tabPage.Location = new System.Drawing.Point(4, 4);
            this.tabPage.Name = "tabPage";
            this.tabPage.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage.Size = new System.Drawing.Size(449, 188);
            this.tabPage.TabIndex = 0;
            this.tabPage.Text = "tabPage1";
            // 
            // ContractDatePicker
            // 
            this.ContractDatePicker.BackColor = System.Drawing.Color.Transparent;
            this.ContractDatePicker.BorderRadius = 1;
            this.ContractDatePicker.Color = System.Drawing.Color.Silver;
            this.ContractDatePicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.ContractDatePicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.ContractDatePicker.DisabledColor = System.Drawing.Color.Gray;
            this.ContractDatePicker.DisplayWeekNumbers = false;
            this.ContractDatePicker.DPHeight = 0;
            this.ContractDatePicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.ContractDatePicker.FillDatePicker = false;
            this.ContractDatePicker.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ContractDatePicker.ForeColor = System.Drawing.Color.Black;
            this.ContractDatePicker.Icon = ((System.Drawing.Image)(resources.GetObject("ContractDatePicker.Icon")));
            this.ContractDatePicker.IconColor = System.Drawing.Color.Gray;
            this.ContractDatePicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.ContractDatePicker.LeftTextMargin = 5;
            this.ContractDatePicker.Location = new System.Drawing.Point(25, 135);
            this.ContractDatePicker.MinDate = new System.DateTime(2022, 12, 19, 5, 46, 23, 989);
            this.ContractDatePicker.MinimumSize = new System.Drawing.Size(4, 32);
            this.ContractDatePicker.Name = "ContractDatePicker";
            this.ContractDatePicker.Size = new System.Drawing.Size(200, 32);
            this.ContractDatePicker.TabIndex = 2;
            this.ContractDatePicker.Value = System.DateTime.Now;
            this.ContractDatePicker.MinDate = System.DateTime.Now;
            this.ContractDatePicker.ValueChanged += new System.EventHandler(this.ContractDatePicker_ValueChanged);
            // 
            // ContractdateLabel
            // 
            this.ContractdateLabel.AllowParentOverrides = false;
            this.ContractdateLabel.AutoEllipsis = false;
            this.ContractdateLabel.CursorType = null;
            this.ContractdateLabel.Font = new System.Drawing.Font("Calibri", 15.75F, System.Drawing.FontStyle.Bold);
            this.ContractdateLabel.ForeColor = System.Drawing.Color.Indigo;
            this.ContractdateLabel.Location = new System.Drawing.Point(25, 103);
            this.ContractdateLabel.Name = "ContractdateLabel";
            this.ContractdateLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ContractdateLabel.Size = new System.Drawing.Size(84, 26);
            this.ContractdateLabel.TabIndex = 31;
            this.ContractdateLabel.Text = "Contract :";
            this.ContractdateLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ContractdateLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ExpirdatePicker
            // 
            this.ExpirdatePicker.BackColor = System.Drawing.Color.Transparent;
            this.ExpirdatePicker.BorderRadius = 1;
            this.ExpirdatePicker.Color = System.Drawing.Color.Silver;
            this.ExpirdatePicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.ExpirdatePicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.ExpirdatePicker.DisabledColor = System.Drawing.Color.Gray;
            this.ExpirdatePicker.DisplayWeekNumbers = false;
            this.ExpirdatePicker.DPHeight = 0;
            this.ExpirdatePicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.ExpirdatePicker.FillDatePicker = false;
            this.ExpirdatePicker.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ExpirdatePicker.ForeColor = System.Drawing.Color.Black;
            this.ExpirdatePicker.Icon = ((System.Drawing.Image)(resources.GetObject("ExpirdatePicker.Icon")));
            this.ExpirdatePicker.IconColor = System.Drawing.Color.Gray;
            this.ExpirdatePicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.ExpirdatePicker.LeftTextMargin = 5;
            this.ExpirdatePicker.Location = new System.Drawing.Point(250, 135);
            this.ExpirdatePicker.MinDate = new System.DateTime(2022, 12, 20, 5, 46, 23, 989);
            this.ExpirdatePicker.MinimumSize = new System.Drawing.Size(4, 32);
            this.ExpirdatePicker.Name = "ExpirdatePicker";
            this.ExpirdatePicker.Size = new System.Drawing.Size(200, 32);
            this.ExpirdatePicker.TabIndex = 3;
            this.ExpirdatePicker.Value = this.ContractDatePicker.Value.AddDays(1);
            this.ExpirdatePicker.MinDate = this.ContractDatePicker.Value.AddDays(1);
            // 
            // ExpirdateLabel
            // 
            this.ExpirdateLabel.AllowParentOverrides = false;
            this.ExpirdateLabel.AutoEllipsis = false;
            this.ExpirdateLabel.CursorType = null;
            this.ExpirdateLabel.Font = new System.Drawing.Font("Calibri", 15.75F, System.Drawing.FontStyle.Bold);
            this.ExpirdateLabel.ForeColor = System.Drawing.Color.Indigo;
            this.ExpirdateLabel.Location = new System.Drawing.Point(250, 103);
            this.ExpirdateLabel.Name = "ExpirdateLabel";
            this.ExpirdateLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ExpirdateLabel.Size = new System.Drawing.Size(54, 26);
            this.ExpirdateLabel.TabIndex = 29;
            this.ExpirdateLabel.Text = "Expir :";
            this.ExpirdateLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ExpirdateLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // GuestIDLabel
            // 
            this.GuestIDLabel.AllowParentOverrides = false;
            this.GuestIDLabel.AutoEllipsis = false;
            this.GuestIDLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.GuestIDLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.GuestIDLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.GuestIDLabel.ForeColor = System.Drawing.Color.Indigo;
            this.GuestIDLabel.Location = new System.Drawing.Point(250, 19);
            this.GuestIDLabel.Name = "GuestIDLabel";
            this.GuestIDLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.GuestIDLabel.Size = new System.Drawing.Size(46, 15);
            this.GuestIDLabel.TabIndex = 17;
            this.GuestIDLabel.Text = "Guest ID";
            this.GuestIDLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.GuestIDLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.GuestIDLabel.Visible = false;
            // 
            // GuestIDBox
            // 
            this.GuestIDBox.AcceptsReturn = false;
            this.GuestIDBox.AcceptsTab = false;
            this.GuestIDBox.AnimationSpeed = 200;
            this.GuestIDBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.GuestIDBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.GuestIDBox.BackColor = System.Drawing.Color.White;
            this.GuestIDBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("GuestIDBox.BackgroundImage")));
            this.GuestIDBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.GuestIDBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.GuestIDBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.GuestIDBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.GuestIDBox.BorderRadius = 7;
            this.GuestIDBox.BorderThickness = 3;
            this.GuestIDBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.GuestIDBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.GuestIDBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.GuestIDBox.DefaultText = "";
            this.GuestIDBox.FillColor = System.Drawing.Color.White;
            this.GuestIDBox.HideSelection = true;
            this.GuestIDBox.IconLeft = null;
            this.GuestIDBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.GuestIDBox.IconPadding = 15;
            this.GuestIDBox.IconRight = null;
            this.GuestIDBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.GuestIDBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.GuestIDBox.Lines = new string[0];
            this.GuestIDBox.Location = new System.Drawing.Point(250, 25);
            this.GuestIDBox.MaxLength = 20;
            this.GuestIDBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.GuestIDBox.Modified = false;
            this.GuestIDBox.Multiline = false;
            this.GuestIDBox.Name = "GuestIDBox";
            stateProperties1.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.GuestIDBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Gray;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.GuestIDBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties3.FillColor = System.Drawing.Color.White;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.GuestIDBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Indigo;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.GuestIDBox.OnIdleState = stateProperties4;
            this.GuestIDBox.Padding = new System.Windows.Forms.Padding(3);
            this.GuestIDBox.PasswordChar = '\0';
            this.GuestIDBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.GuestIDBox.PlaceholderText = "Guest ID";
            this.GuestIDBox.ReadOnly = false;
            this.GuestIDBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.GuestIDBox.SelectedText = "";
            this.GuestIDBox.SelectionLength = 0;
            this.GuestIDBox.SelectionStart = 0;
            this.GuestIDBox.ShortcutsEnabled = true;
            this.GuestIDBox.Size = new System.Drawing.Size(200, 50);
            this.GuestIDBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.GuestIDBox.TabIndex = 1;
            this.GuestIDBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.GuestIDBox.TextMarginBottom = 0;
            this.GuestIDBox.TextMarginLeft = 10;
            this.GuestIDBox.TextMarginTop = 0;
            this.GuestIDBox.TextPlaceholder = "Guest ID";
            this.GuestIDBox.UseSystemPasswordChar = false;
            this.GuestIDBox.WordWrap = true;
            this.GuestIDBox.TextChanged += new System.EventHandler(this.GuestIDBox_TextChanged);
            // 
            // RoomIDLabel
            // 
            this.RoomIDLabel.AllowParentOverrides = false;
            this.RoomIDLabel.AutoEllipsis = false;
            this.RoomIDLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.RoomIDLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.RoomIDLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.RoomIDLabel.ForeColor = System.Drawing.Color.Indigo;
            this.RoomIDLabel.Location = new System.Drawing.Point(25, 19);
            this.RoomIDLabel.Name = "RoomIDLabel";
            this.RoomIDLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.RoomIDLabel.Size = new System.Drawing.Size(46, 15);
            this.RoomIDLabel.TabIndex = 13;
            this.RoomIDLabel.Text = "Room ID";
            this.RoomIDLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.RoomIDLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.RoomIDLabel.Visible = false;
            // 
            // RoomIDBox
            // 
            this.RoomIDBox.AcceptsReturn = false;
            this.RoomIDBox.AcceptsTab = false;
            this.RoomIDBox.AnimationSpeed = 200;
            this.RoomIDBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.RoomIDBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.RoomIDBox.BackColor = System.Drawing.Color.White;
            this.RoomIDBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RoomIDBox.BackgroundImage")));
            this.RoomIDBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.RoomIDBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.RoomIDBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.RoomIDBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.RoomIDBox.BorderRadius = 7;
            this.RoomIDBox.BorderThickness = 3;
            this.RoomIDBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.RoomIDBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomIDBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RoomIDBox.DefaultText = "";
            this.RoomIDBox.FillColor = System.Drawing.Color.White;
            this.RoomIDBox.HideSelection = true;
            this.RoomIDBox.IconLeft = null;
            this.RoomIDBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomIDBox.IconPadding = 15;
            this.RoomIDBox.IconRight = null;
            this.RoomIDBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomIDBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.RoomIDBox.Lines = new string[0];
            this.RoomIDBox.Location = new System.Drawing.Point(25, 25);
            this.RoomIDBox.MaxLength = 20;
            this.RoomIDBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.RoomIDBox.Modified = false;
            this.RoomIDBox.Multiline = false;
            this.RoomIDBox.Name = "RoomIDBox";
            stateProperties5.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties5.FillColor = System.Drawing.Color.White;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomIDBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Gray;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.RoomIDBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties7.FillColor = System.Drawing.Color.White;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomIDBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Indigo;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomIDBox.OnIdleState = stateProperties8;
            this.RoomIDBox.Padding = new System.Windows.Forms.Padding(3);
            this.RoomIDBox.PasswordChar = '\0';
            this.RoomIDBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.RoomIDBox.PlaceholderText = "Room ID";
            this.RoomIDBox.ReadOnly = false;
            this.RoomIDBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.RoomIDBox.SelectedText = "";
            this.RoomIDBox.SelectionLength = 0;
            this.RoomIDBox.SelectionStart = 0;
            this.RoomIDBox.ShortcutsEnabled = true;
            this.RoomIDBox.Size = new System.Drawing.Size(200, 50);
            this.RoomIDBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.RoomIDBox.TabIndex = 0;
            this.RoomIDBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.RoomIDBox.TextMarginBottom = 0;
            this.RoomIDBox.TextMarginLeft = 10;
            this.RoomIDBox.TextMarginTop = 0;
            this.RoomIDBox.TextPlaceholder = "Room ID";
            this.RoomIDBox.UseSystemPasswordChar = false;
            this.RoomIDBox.WordWrap = true;
            this.RoomIDBox.TextChanged += new System.EventHandler(this.RoomIDBox_TextChanged);
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.SystemColors.Control;
            this.tabPage2.Controls.Add(this.RoomTypeLabel);
            this.tabPage2.Controls.Add(this.PriceLabel);
            this.tabPage2.Controls.Add(this.PriceBox);
            this.tabPage2.Controls.Add(this.FloorLabel);
            this.tabPage2.Controls.Add(this.FloorBox);
            this.tabPage2.Controls.Add(this.SectionLabel);
            this.tabPage2.Controls.Add(this.SectionBox);
            this.tabPage2.Controls.Add(this.RoomTypeBox);
            this.tabPage2.Controls.Add(this.RoomNumberLabel);
            this.tabPage2.Controls.Add(this.RoomNumberBox);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(449, 188);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            // 
            // RoomTypeLabel
            // 
            this.RoomTypeLabel.AllowParentOverrides = false;
            this.RoomTypeLabel.AutoEllipsis = false;
            this.RoomTypeLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.RoomTypeLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.RoomTypeLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.RoomTypeLabel.ForeColor = System.Drawing.Color.Indigo;
            this.RoomTypeLabel.Location = new System.Drawing.Point(25, 129);
            this.RoomTypeLabel.Name = "RoomTypeLabel";
            this.RoomTypeLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.RoomTypeLabel.Size = new System.Drawing.Size(61, 15);
            this.RoomTypeLabel.TabIndex = 17;
            this.RoomTypeLabel.Text = "Room Type";
            this.RoomTypeLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.RoomTypeLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.RoomTypeLabel.Visible = false;
            // 
            // PriceLabel
            // 
            this.PriceLabel.AllowParentOverrides = false;
            this.PriceLabel.AutoEllipsis = false;
            this.PriceLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.PriceLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.PriceLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.PriceLabel.ForeColor = System.Drawing.Color.Indigo;
            this.PriceLabel.Location = new System.Drawing.Point(25, 64);
            this.PriceLabel.Name = "PriceLabel";
            this.PriceLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.PriceLabel.Size = new System.Drawing.Size(27, 15);
            this.PriceLabel.TabIndex = 25;
            this.PriceLabel.Text = "Price";
            this.PriceLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.PriceLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.PriceLabel.Visible = false;
            // 
            // PriceBox
            // 
            this.PriceBox.AcceptsReturn = false;
            this.PriceBox.AcceptsTab = false;
            this.PriceBox.AnimationSpeed = 200;
            this.PriceBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PriceBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PriceBox.BackColor = System.Drawing.Color.White;
            this.PriceBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PriceBox.BackgroundImage")));
            this.PriceBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.PriceBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.PriceBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.PriceBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.PriceBox.BorderRadius = 7;
            this.PriceBox.BorderThickness = 3;
            this.PriceBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PriceBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PriceBox.DefaultText = "";
            this.PriceBox.FillColor = System.Drawing.Color.White;
            this.PriceBox.HideSelection = true;
            this.PriceBox.IconLeft = null;
            this.PriceBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.IconPadding = 15;
            this.PriceBox.IconRight = null;
            this.PriceBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.PriceBox.Lines = new string[0];
            this.PriceBox.Location = new System.Drawing.Point(25, 70);
            this.PriceBox.MaxLength = 20;
            this.PriceBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PriceBox.Modified = false;
            this.PriceBox.Multiline = false;
            this.PriceBox.Name = "PriceBox";
            stateProperties9.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties9.FillColor = System.Drawing.Color.White;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Gray;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PriceBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties11.FillColor = System.Drawing.Color.White;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Indigo;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnIdleState = stateProperties12;
            this.PriceBox.Padding = new System.Windows.Forms.Padding(3);
            this.PriceBox.PasswordChar = '\0';
            this.PriceBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.PriceBox.PlaceholderText = "Price";
            this.PriceBox.ReadOnly = false;
            this.PriceBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PriceBox.SelectedText = "";
            this.PriceBox.SelectionLength = 0;
            this.PriceBox.SelectionStart = 0;
            this.PriceBox.ShortcutsEnabled = true;
            this.PriceBox.Size = new System.Drawing.Size(200, 50);
            this.PriceBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.PriceBox.TabIndex = 2;
            this.PriceBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PriceBox.TextMarginBottom = 0;
            this.PriceBox.TextMarginLeft = 10;
            this.PriceBox.TextMarginTop = 0;
            this.PriceBox.TextPlaceholder = "Price";
            this.PriceBox.UseSystemPasswordChar = false;
            this.PriceBox.WordWrap = true;
            this.PriceBox.TextChanged += new System.EventHandler(this.PriceBox_TextChanged);
            // 
            // FloorLabel
            // 
            this.FloorLabel.AllowParentOverrides = false;
            this.FloorLabel.AutoEllipsis = false;
            this.FloorLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.FloorLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.FloorLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.FloorLabel.ForeColor = System.Drawing.Color.Indigo;
            this.FloorLabel.Location = new System.Drawing.Point(250, 64);
            this.FloorLabel.Name = "FloorLabel";
            this.FloorLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.FloorLabel.Size = new System.Drawing.Size(28, 15);
            this.FloorLabel.TabIndex = 23;
            this.FloorLabel.Text = "Floor";
            this.FloorLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.FloorLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.FloorLabel.Visible = false;
            // 
            // FloorBox
            // 
            this.FloorBox.AcceptsReturn = false;
            this.FloorBox.AcceptsTab = false;
            this.FloorBox.AnimationSpeed = 200;
            this.FloorBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.FloorBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.FloorBox.BackColor = System.Drawing.Color.White;
            this.FloorBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("FloorBox.BackgroundImage")));
            this.FloorBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.FloorBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.FloorBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.FloorBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.FloorBox.BorderRadius = 7;
            this.FloorBox.BorderThickness = 3;
            this.FloorBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.FloorBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.FloorBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FloorBox.DefaultText = "";
            this.FloorBox.FillColor = System.Drawing.Color.White;
            this.FloorBox.HideSelection = true;
            this.FloorBox.IconLeft = null;
            this.FloorBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.FloorBox.IconPadding = 15;
            this.FloorBox.IconRight = null;
            this.FloorBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.FloorBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.FloorBox.Lines = new string[0];
            this.FloorBox.Location = new System.Drawing.Point(250, 70);
            this.FloorBox.MaxLength = 20;
            this.FloorBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.FloorBox.Modified = false;
            this.FloorBox.Multiline = false;
            this.FloorBox.Name = "FloorBox";
            stateProperties13.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties13.FillColor = System.Drawing.Color.White;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FloorBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Gray;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.FloorBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties15.FillColor = System.Drawing.Color.White;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FloorBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Indigo;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FloorBox.OnIdleState = stateProperties16;
            this.FloorBox.Padding = new System.Windows.Forms.Padding(3);
            this.FloorBox.PasswordChar = '\0';
            this.FloorBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.FloorBox.PlaceholderText = "Floor";
            this.FloorBox.ReadOnly = false;
            this.FloorBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.FloorBox.SelectedText = "";
            this.FloorBox.SelectionLength = 0;
            this.FloorBox.SelectionStart = 0;
            this.FloorBox.ShortcutsEnabled = true;
            this.FloorBox.Size = new System.Drawing.Size(200, 50);
            this.FloorBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.FloorBox.TabIndex = 3;
            this.FloorBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.FloorBox.TextMarginBottom = 0;
            this.FloorBox.TextMarginLeft = 10;
            this.FloorBox.TextMarginTop = 0;
            this.FloorBox.TextPlaceholder = "Floor";
            this.FloorBox.UseSystemPasswordChar = false;
            this.FloorBox.WordWrap = true;
            this.FloorBox.TextChanged += new System.EventHandler(this.FloorBox_TextChanged);
            // 
            // SectionLabel
            // 
            this.SectionLabel.AllowParentOverrides = false;
            this.SectionLabel.AutoEllipsis = false;
            this.SectionLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.SectionLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.SectionLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.SectionLabel.ForeColor = System.Drawing.Color.Indigo;
            this.SectionLabel.Location = new System.Drawing.Point(25, -1);
            this.SectionLabel.Name = "SectionLabel";
            this.SectionLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.SectionLabel.Size = new System.Drawing.Size(40, 15);
            this.SectionLabel.TabIndex = 21;
            this.SectionLabel.Text = "Section";
            this.SectionLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.SectionLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.SectionLabel.Visible = false;
            // 
            // SectionBox
            // 
            this.SectionBox.AcceptsReturn = false;
            this.SectionBox.AcceptsTab = false;
            this.SectionBox.AnimationSpeed = 200;
            this.SectionBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.SectionBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.SectionBox.BackColor = System.Drawing.Color.White;
            this.SectionBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SectionBox.BackgroundImage")));
            this.SectionBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.SectionBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.SectionBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.SectionBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.SectionBox.BorderRadius = 7;
            this.SectionBox.BorderThickness = 3;
            this.SectionBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.SectionBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.SectionBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SectionBox.DefaultText = "";
            this.SectionBox.FillColor = System.Drawing.Color.White;
            this.SectionBox.HideSelection = true;
            this.SectionBox.IconLeft = null;
            this.SectionBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.SectionBox.IconPadding = 15;
            this.SectionBox.IconRight = null;
            this.SectionBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.SectionBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.SectionBox.Lines = new string[0];
            this.SectionBox.Location = new System.Drawing.Point(25, 5);
            this.SectionBox.MaxLength = 20;
            this.SectionBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.SectionBox.Modified = false;
            this.SectionBox.Multiline = false;
            this.SectionBox.Name = "SectionBox";
            stateProperties17.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties17.FillColor = System.Drawing.Color.White;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SectionBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Gray;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.SectionBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties19.FillColor = System.Drawing.Color.White;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SectionBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Indigo;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SectionBox.OnIdleState = stateProperties20;
            this.SectionBox.Padding = new System.Windows.Forms.Padding(3);
            this.SectionBox.PasswordChar = '\0';
            this.SectionBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.SectionBox.PlaceholderText = "Section";
            this.SectionBox.ReadOnly = false;
            this.SectionBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.SectionBox.SelectedText = "";
            this.SectionBox.SelectionLength = 0;
            this.SectionBox.SelectionStart = 0;
            this.SectionBox.ShortcutsEnabled = true;
            this.SectionBox.Size = new System.Drawing.Size(200, 50);
            this.SectionBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.SectionBox.TabIndex = 0;
            this.SectionBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.SectionBox.TextMarginBottom = 0;
            this.SectionBox.TextMarginLeft = 10;
            this.SectionBox.TextMarginTop = 0;
            this.SectionBox.TextPlaceholder = "Section";
            this.SectionBox.UseSystemPasswordChar = false;
            this.SectionBox.WordWrap = true;
            this.SectionBox.TextChanged += new System.EventHandler(this.SectionBox_TextChanged);
            // 
            // RoomTypeBox
            // 
            this.RoomTypeBox.AcceptsReturn = false;
            this.RoomTypeBox.AcceptsTab = false;
            this.RoomTypeBox.AnimationSpeed = 200;
            this.RoomTypeBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.RoomTypeBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.RoomTypeBox.BackColor = System.Drawing.Color.White;
            this.RoomTypeBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RoomTypeBox.BackgroundImage")));
            this.RoomTypeBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.RoomTypeBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.RoomTypeBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.RoomTypeBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.RoomTypeBox.BorderRadius = 7;
            this.RoomTypeBox.BorderThickness = 3;
            this.RoomTypeBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.RoomTypeBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomTypeBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RoomTypeBox.DefaultText = "";
            this.RoomTypeBox.FillColor = System.Drawing.Color.White;
            this.RoomTypeBox.HideSelection = true;
            this.RoomTypeBox.IconLeft = null;
            this.RoomTypeBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomTypeBox.IconPadding = 15;
            this.RoomTypeBox.IconRight = null;
            this.RoomTypeBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomTypeBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.RoomTypeBox.Lines = new string[0];
            this.RoomTypeBox.Location = new System.Drawing.Point(25, 135);
            this.RoomTypeBox.MaxLength = 20;
            this.RoomTypeBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.RoomTypeBox.Modified = false;
            this.RoomTypeBox.Multiline = false;
            this.RoomTypeBox.Name = "RoomTypeBox";
            stateProperties21.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties21.FillColor = System.Drawing.Color.White;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomTypeBox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Gray;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.RoomTypeBox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties23.FillColor = System.Drawing.Color.White;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomTypeBox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Indigo;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomTypeBox.OnIdleState = stateProperties24;
            this.RoomTypeBox.Padding = new System.Windows.Forms.Padding(3);
            this.RoomTypeBox.PasswordChar = '\0';
            this.RoomTypeBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.RoomTypeBox.PlaceholderText = "Room Type";
            this.RoomTypeBox.ReadOnly = false;
            this.RoomTypeBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.RoomTypeBox.SelectedText = "";
            this.RoomTypeBox.SelectionLength = 0;
            this.RoomTypeBox.SelectionStart = 0;
            this.RoomTypeBox.ShortcutsEnabled = true;
            this.RoomTypeBox.Size = new System.Drawing.Size(425, 50);
            this.RoomTypeBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.RoomTypeBox.TabIndex = 4;
            this.RoomTypeBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.RoomTypeBox.TextMarginBottom = 0;
            this.RoomTypeBox.TextMarginLeft = 10;
            this.RoomTypeBox.TextMarginTop = 0;
            this.RoomTypeBox.TextPlaceholder = "Room Type";
            this.RoomTypeBox.UseSystemPasswordChar = false;
            this.RoomTypeBox.WordWrap = true;
            this.RoomTypeBox.TextChanged += new System.EventHandler(this.RoomTypeBox_TextChanged);
            // 
            // RoomNumberLabel
            // 
            this.RoomNumberLabel.AllowParentOverrides = false;
            this.RoomNumberLabel.AutoEllipsis = false;
            this.RoomNumberLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.RoomNumberLabel.CursorType = System.Windows.Forms.Cursors.Default;
            this.RoomNumberLabel.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold);
            this.RoomNumberLabel.ForeColor = System.Drawing.Color.Indigo;
            this.RoomNumberLabel.Location = new System.Drawing.Point(250, -1);
            this.RoomNumberLabel.Name = "RoomNumberLabel";
            this.RoomNumberLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.RoomNumberLabel.Size = new System.Drawing.Size(81, 15);
            this.RoomNumberLabel.TabIndex = 19;
            this.RoomNumberLabel.Text = "Room Number";
            this.RoomNumberLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.RoomNumberLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.RoomNumberLabel.Visible = false;
            // 
            // RoomNumberBox
            // 
            this.RoomNumberBox.AcceptsReturn = false;
            this.RoomNumberBox.AcceptsTab = false;
            this.RoomNumberBox.AnimationSpeed = 200;
            this.RoomNumberBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.RoomNumberBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.RoomNumberBox.BackColor = System.Drawing.Color.White;
            this.RoomNumberBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RoomNumberBox.BackgroundImage")));
            this.RoomNumberBox.BorderColorActive = System.Drawing.Color.SlateBlue;
            this.RoomNumberBox.BorderColorDisabled = System.Drawing.Color.Gray;
            this.RoomNumberBox.BorderColorHover = System.Drawing.Color.BlueViolet;
            this.RoomNumberBox.BorderColorIdle = System.Drawing.Color.Indigo;
            this.RoomNumberBox.BorderRadius = 7;
            this.RoomNumberBox.BorderThickness = 3;
            this.RoomNumberBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.RoomNumberBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomNumberBox.DefaultFont = new System.Drawing.Font("Calibri", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RoomNumberBox.DefaultText = "";
            this.RoomNumberBox.FillColor = System.Drawing.Color.White;
            this.RoomNumberBox.HideSelection = true;
            this.RoomNumberBox.IconLeft = null;
            this.RoomNumberBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomNumberBox.IconPadding = 15;
            this.RoomNumberBox.IconRight = null;
            this.RoomNumberBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoomNumberBox.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.RoomNumberBox.Lines = new string[0];
            this.RoomNumberBox.Location = new System.Drawing.Point(250, 5);
            this.RoomNumberBox.MaxLength = 20;
            this.RoomNumberBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.RoomNumberBox.Modified = false;
            this.RoomNumberBox.Multiline = false;
            this.RoomNumberBox.Name = "RoomNumberBox";
            stateProperties25.BorderColor = System.Drawing.Color.SlateBlue;
            stateProperties25.FillColor = System.Drawing.Color.White;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomNumberBox.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Gray;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.RoomNumberBox.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.BlueViolet;
            stateProperties27.FillColor = System.Drawing.Color.White;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomNumberBox.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Indigo;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoomNumberBox.OnIdleState = stateProperties28;
            this.RoomNumberBox.Padding = new System.Windows.Forms.Padding(3);
            this.RoomNumberBox.PasswordChar = '\0';
            this.RoomNumberBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(149)))), ((int)(((byte)(223)))));
            this.RoomNumberBox.PlaceholderText = "Room Number";
            this.RoomNumberBox.ReadOnly = false;
            this.RoomNumberBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.RoomNumberBox.SelectedText = "";
            this.RoomNumberBox.SelectionLength = 0;
            this.RoomNumberBox.SelectionStart = 0;
            this.RoomNumberBox.ShortcutsEnabled = true;
            this.RoomNumberBox.Size = new System.Drawing.Size(200, 50);
            this.RoomNumberBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.RoomNumberBox.TabIndex = 1;
            this.RoomNumberBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.RoomNumberBox.TextMarginBottom = 0;
            this.RoomNumberBox.TextMarginLeft = 10;
            this.RoomNumberBox.TextMarginTop = 0;
            this.RoomNumberBox.TextPlaceholder = "Room Number";
            this.RoomNumberBox.UseSystemPasswordChar = false;
            this.RoomNumberBox.WordWrap = true;
            this.RoomNumberBox.TextChanged += new System.EventHandler(this.RoomNumberBox_TextChanged);
            // 
            // Tab2
            // 
            this.Tab2.AllowAnimations = true;
            this.Tab2.AllowMouseEffects = true;
            this.Tab2.AllowToggling = false;
            this.Tab2.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.Tab2.AnimationSpeed = 200;
            this.Tab2.AutoGenerateColors = false;
            this.Tab2.AutoRoundBorders = false;
            this.Tab2.AutoSizeLeftIcon = true;
            this.Tab2.AutoSizeRightIcon = true;
            this.Tab2.BackColor = System.Drawing.Color.Transparent;
            this.Tab2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Tab2.BackgroundImage")));
            this.Tab2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.ButtonText = "Reserve";
            this.Tab2.ButtonTextMarginLeft = 0;
            this.Tab2.ColorContrastOnClick = 45;
            this.Tab2.ColorContrastOnHover = 45;
            this.Tab2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = false;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = false;
            borderEdges3.TopRight = true;
            this.Tab2.CustomizableEdges = borderEdges3;
            this.Tab2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Tab2.DisabledBorderColor = System.Drawing.Color.Indigo;
            this.Tab2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.DisabledForecolor = System.Drawing.Color.White;
            this.Tab2.Enabled = false;
            this.Tab2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Tab2.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Tab2.ForeColor = System.Drawing.Color.White;
            this.Tab2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Tab2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Tab2.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Tab2.IconMarginLeft = 11;
            this.Tab2.IconPadding = 10;
            this.Tab2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Tab2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Tab2.IconRightPadding = new System.Windows.Forms.Padding(15);
            this.Tab2.IconSize = 25;
            this.Tab2.IdleBorderColor = System.Drawing.Color.Indigo;
            this.Tab2.IdleBorderRadius = 50;
            this.Tab2.IdleBorderThickness = 1;
            this.Tab2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.IdleIconLeftImage = null;
            this.Tab2.IdleIconRightImage = null;
            this.Tab2.IndicateFocus = false;
            this.Tab2.Location = new System.Drawing.Point(255, 50);
            this.Tab2.Name = "Tab2";
            this.Tab2.OnDisabledState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab2.OnDisabledState.BorderRadius = 50;
            this.Tab2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.OnDisabledState.BorderThickness = 1;
            this.Tab2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.Tab2.OnDisabledState.IconLeftImage = null;
            this.Tab2.OnDisabledState.IconRightImage = null;
            this.Tab2.onHoverState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab2.onHoverState.BorderRadius = 50;
            this.Tab2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.onHoverState.BorderThickness = 1;
            this.Tab2.onHoverState.FillColor = System.Drawing.Color.BlueViolet;
            this.Tab2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Tab2.onHoverState.IconLeftImage = null;
            this.Tab2.onHoverState.IconRightImage = null;
            this.Tab2.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab2.OnIdleState.BorderRadius = 50;
            this.Tab2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.OnIdleState.BorderThickness = 1;
            this.Tab2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Tab2.OnIdleState.IconLeftImage = null;
            this.Tab2.OnIdleState.IconRightImage = null;
            this.Tab2.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab2.OnPressedState.BorderRadius = 50;
            this.Tab2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab2.OnPressedState.BorderThickness = 1;
            this.Tab2.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.Tab2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Tab2.OnPressedState.IconLeftImage = null;
            this.Tab2.OnPressedState.IconRightImage = null;
            this.Tab2.Size = new System.Drawing.Size(125, 50);
            this.Tab2.TabIndex = 18;
            this.Tab2.TabStop = false;
            this.Tab2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Tab2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Tab2.TextMarginLeft = 0;
            this.Tab2.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.Tab2.UseDefaultRadiusAndThickness = true;
            this.Tab2.Click += new System.EventHandler(this.Tab2_Click);
            // 
            // Tab1
            // 
            this.Tab1.AllowAnimations = true;
            this.Tab1.AllowMouseEffects = true;
            this.Tab1.AllowToggling = false;
            this.Tab1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.Tab1.AnimationSpeed = 200;
            this.Tab1.AutoGenerateColors = false;
            this.Tab1.AutoRoundBorders = false;
            this.Tab1.AutoSizeLeftIcon = true;
            this.Tab1.AutoSizeRightIcon = true;
            this.Tab1.BackColor = System.Drawing.Color.Transparent;
            this.Tab1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Tab1.BackgroundImage")));
            this.Tab1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.ButtonText = "Room";
            this.Tab1.ButtonTextMarginLeft = 0;
            this.Tab1.ColorContrastOnClick = 45;
            this.Tab1.ColorContrastOnHover = 45;
            this.Tab1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = false;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = false;
            this.Tab1.CustomizableEdges = borderEdges4;
            this.Tab1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Tab1.DisabledBorderColor = System.Drawing.Color.Indigo;
            this.Tab1.DisabledFillColor = System.Drawing.Color.Indigo;
            this.Tab1.DisabledForecolor = System.Drawing.Color.White;
            this.Tab1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Tab1.Font = new System.Drawing.Font("Calibri", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Tab1.ForeColor = System.Drawing.Color.White;
            this.Tab1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Tab1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Tab1.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Tab1.IconMarginLeft = 11;
            this.Tab1.IconPadding = 10;
            this.Tab1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Tab1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Tab1.IconRightPadding = new System.Windows.Forms.Padding(15);
            this.Tab1.IconSize = 25;
            this.Tab1.IdleBorderColor = System.Drawing.Color.Indigo;
            this.Tab1.IdleBorderRadius = 50;
            this.Tab1.IdleBorderThickness = 1;
            this.Tab1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab1.IdleIconLeftImage = null;
            this.Tab1.IdleIconRightImage = null;
            this.Tab1.IndicateFocus = false;
            this.Tab1.Location = new System.Drawing.Point(131, 50);
            this.Tab1.Name = "Tab1";
            this.Tab1.OnDisabledState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab1.OnDisabledState.BorderRadius = 50;
            this.Tab1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.OnDisabledState.BorderThickness = 1;
            this.Tab1.OnDisabledState.FillColor = System.Drawing.Color.Indigo;
            this.Tab1.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.Tab1.OnDisabledState.IconLeftImage = null;
            this.Tab1.OnDisabledState.IconRightImage = null;
            this.Tab1.onHoverState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab1.onHoverState.BorderRadius = 50;
            this.Tab1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.onHoverState.BorderThickness = 1;
            this.Tab1.onHoverState.FillColor = System.Drawing.Color.BlueViolet;
            this.Tab1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Tab1.onHoverState.IconLeftImage = null;
            this.Tab1.onHoverState.IconRightImage = null;
            this.Tab1.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.Tab1.OnIdleState.BorderRadius = 50;
            this.Tab1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.OnIdleState.BorderThickness = 1;
            this.Tab1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(28)))), ((int)(((byte)(152)))));
            this.Tab1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Tab1.OnIdleState.IconLeftImage = null;
            this.Tab1.OnIdleState.IconRightImage = null;
            this.Tab1.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.Tab1.OnPressedState.BorderRadius = 50;
            this.Tab1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Tab1.OnPressedState.BorderThickness = 1;
            this.Tab1.OnPressedState.FillColor = System.Drawing.Color.Indigo;
            this.Tab1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Tab1.OnPressedState.IconLeftImage = null;
            this.Tab1.OnPressedState.IconRightImage = null;
            this.Tab1.Size = new System.Drawing.Size(125, 50);
            this.Tab1.TabIndex = 17;
            this.Tab1.TabStop = false;
            this.Tab1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Tab1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Tab1.TextMarginLeft = 0;
            this.Tab1.TextPadding = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.Tab1.UseDefaultRadiusAndThickness = true;
            this.Tab1.Click += new System.EventHandler(this.Tab1_Click);
            // 
            // AddRoomsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(500, 382);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AddRoomsForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "AddOrdersForm";
            this.panel1.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.Pages.ResumeLayout(false);
            this.tabPage.ResumeLayout(false);
            this.tabPage.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel Title;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AddBt;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btClose;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Tab2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Tab1;
        private Bunifu.UI.WinForms.BunifuLabel RoomIDLabel;
        private Bunifu.UI.WinForms.BunifuTextBox RoomIDBox;
        private Bunifu.UI.WinForms.BunifuPages Pages;
        private System.Windows.Forms.TabPage tabPage;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuLabel GuestIDLabel;
        private Bunifu.UI.WinForms.BunifuTextBox GuestIDBox;
        private Bunifu.UI.WinForms.BunifuDatePicker ContractDatePicker;
        private Bunifu.UI.WinForms.BunifuLabel ContractdateLabel;
        private Bunifu.UI.WinForms.BunifuDatePicker ExpirdatePicker;
        private Bunifu.UI.WinForms.BunifuLabel ExpirdateLabel;
        private Bunifu.UI.WinForms.BunifuLabel PriceLabel;
        private Bunifu.UI.WinForms.BunifuTextBox PriceBox;
        private Bunifu.UI.WinForms.BunifuLabel FloorLabel;
        private Bunifu.UI.WinForms.BunifuTextBox FloorBox;
        private Bunifu.UI.WinForms.BunifuLabel SectionLabel;
        private Bunifu.UI.WinForms.BunifuTextBox SectionBox;
        private Bunifu.UI.WinForms.BunifuLabel RoomNumberLabel;
        private Bunifu.UI.WinForms.BunifuTextBox RoomNumberBox;
        private Bunifu.UI.WinForms.BunifuLabel RoomTypeLabel;
        private Bunifu.UI.WinForms.BunifuTextBox RoomTypeBox;
    }
}